package com.ibm.bbva.ctacte.bean;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Carterizacion generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_CARTERIZACION", schema = "CONELE")
public class Carterizacion implements Serializable {

	private static final long serialVersionUID = -184973829513689647L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProductoFk", column = @Column(name = "ID_PRODUCTO_FK", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "idTerritorioFk", column = @Column(name = "ID_TERRITORIO_FK", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "idEmpleadoFk", column = @Column(name = "ID_EMPLEADO_FK", nullable = false, precision = 10, scale = 0)) })
	private CarterizacionId id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_EMPLEADO_FK", nullable = false, insertable = false, updatable = false)
	private Empleado empleado;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PRODUCTO_FK", nullable = false, insertable = false, updatable = false)
	private ProductoCE productoCE;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TERRITORIO_FK", nullable = false, insertable = false, updatable = false)
	private Territorio territorio;
	
	@Column(name = "CODIGO", length = 10)
	private String codigo;
	
	@Column(name = "DESCRIPCION", length = 50)
	private String descripcion;

	public Carterizacion() {
	}

	public CarterizacionId getId() {
		return id;
	}

	public void setId(CarterizacionId id) {
		this.id = id;
	}

	public Empleado getEmpleado() {
		return empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public ProductoCE getProductoCE() {
		return productoCE;
	}

	public void setProducto(ProductoCE productoCE) {
		this.productoCE = productoCE;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Territorio getTerritorio() {
		return territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

}
