package com.ibm.bbva.ctacte.bean;
// default package
// Generated 14/05/2012 10:37:52 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TareaPerfil generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_TAREA_PERFIL_CC", schema = "CONELE")
public class TareaPerfil implements java.io.Serializable {

	private static final long serialVersionUID = 1938409395703264360L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PERFIL_FK", nullable = false)
	private Perfil perfil;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TAREA_CC_FK", nullable = false)
	private Tarea tarea;

	public TareaPerfil() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Perfil getPerfil() {
		return perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public Tarea getTarea() {
		return tarea;
	}

	public void setTarea(Tarea tarea) {
		this.tarea = tarea;
	}

}
