//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ibm.bbva.harec.client;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Contrato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contrato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aliasProducto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contrato" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="moneda" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="situacionContrato" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tarjeta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="situacionTarjeta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bloqueoTarjeta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contrato", propOrder = {
    "aliasProducto",
    "contrato",
    "moneda",
    "situacionContrato",
    "tarjeta",
    "situacionTarjeta",
    "bloqueoTarjeta"
})
public class Contrato {

    @XmlElement(required = true)
    protected String aliasProducto;
    @XmlElement(required = true)
    protected String contrato;
    @XmlElement(required = true)
    protected String moneda;
    @XmlElement(required = true)
    protected String situacionContrato;
    @XmlElement(required = true)
    protected String tarjeta;
    @XmlElement(required = true)
    protected String situacionTarjeta;
    @XmlElement(required = true)
    protected String bloqueoTarjeta;

    /**
     * Gets the value of the aliasProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasProducto() {
        return aliasProducto;
    }

    /**
     * Sets the value of the aliasProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasProducto(String value) {
        this.aliasProducto = value;
    }

    /**
     * Gets the value of the contrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContrato() {
        return contrato;
    }

    /**
     * Sets the value of the contrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContrato(String value) {
        this.contrato = value;
    }

    /**
     * Gets the value of the moneda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoneda() {
        return moneda;
    }

    /**
     * Sets the value of the moneda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoneda(String value) {
        this.moneda = value;
    }

    /**
     * Gets the value of the situacionContrato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSituacionContrato() {
        return situacionContrato;
    }

    /**
     * Sets the value of the situacionContrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSituacionContrato(String value) {
        this.situacionContrato = value;
    }

    /**
     * Gets the value of the tarjeta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarjeta() {
        return tarjeta;
    }

    /**
     * Sets the value of the tarjeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarjeta(String value) {
        this.tarjeta = value;
    }

    /**
     * Gets the value of the situacionTarjeta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSituacionTarjeta() {
        return situacionTarjeta;
    }

    /**
     * Sets the value of the situacionTarjeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSituacionTarjeta(String value) {
        this.situacionTarjeta = value;
    }

    /**
     * Gets the value of the bloqueoTarjeta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloqueoTarjeta() {
        return bloqueoTarjeta;
    }

    /**
     * Sets the value of the bloqueoTarjeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloqueoTarjeta(String value) {
        this.bloqueoTarjeta = value;
    }

}
