//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ibm.bbva.reniec.consultapornombres;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.grupobbva.pe.sir.ents.body.consultapornombres package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultaPorNombresResponse_QNAME = new QName("http://pe.grupobbva.com/SIR/ents/body/consultaPorNombres", "consultaPorNombresResponse");
    private final static QName _ConsultaPorNombresRequest_QNAME = new QName("http://pe.grupobbva.com/SIR/ents/body/consultaPorNombres", "consultaPorNombresRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.grupobbva.pe.sir.ents.body.consultapornombres
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsultaPorNombresResponse }
     * 
     */
    public ConsultaPorNombresResponse createConsultaPorNombresResponse() {
        return new ConsultaPorNombresResponse();
    }

    /**
     * Create an instance of {@link ConsultaPorNombresRequest }
     * 
     */
    public ConsultaPorNombresRequest createConsultaPorNombresRequest() {
        return new ConsultaPorNombresRequest();
    }

    /**
     * Create an instance of {@link ListaDatosPersona }
     * 
     */
    public ListaDatosPersona createListaDatosPersona() {
        return new ListaDatosPersona();
    }

    /**
     * Create an instance of {@link DatosPersona }
     * 
     */
    public DatosPersona createDatosPersona() {
        return new DatosPersona();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaPorNombresResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pe.grupobbva.com/SIR/ents/body/consultaPorNombres", name = "consultaPorNombresResponse")
    public JAXBElement<ConsultaPorNombresResponse> createConsultaPorNombresResponse(ConsultaPorNombresResponse value) {
        return new JAXBElement<ConsultaPorNombresResponse>(_ConsultaPorNombresResponse_QNAME, ConsultaPorNombresResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultaPorNombresRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pe.grupobbva.com/SIR/ents/body/consultaPorNombres", name = "consultaPorNombresRequest")
    public JAXBElement<ConsultaPorNombresRequest> createConsultaPorNombresRequest(ConsultaPorNombresRequest value) {
        return new JAXBElement<ConsultaPorNombresRequest>(_ConsultaPorNombresRequest_QNAME, ConsultaPorNombresRequest.class, null, value);
    }

}
