//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package pe.com.grupobbva.accpj.pagser;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "PagoServicio_Service", targetNamespace = "http://grupobbva.com.pe/accpj/pagser/", wsdlLocation = "META-INF/wsdl/ACCPJ_PagoServicioService.wsdl")
public class PagoServicioService
    extends Service
{

    private final static URL PAGOSERVICIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAGOSERVICIOSERVICE_EXCEPTION;
    private final static QName PAGOSERVICIOSERVICE_QNAME = new QName("http://grupobbva.com.pe/accpj/pagser/", "PagoServicio_Service");

    static {
            PAGOSERVICIOSERVICE_WSDL_LOCATION = pe.com.grupobbva.accpj.pagser.PagoServicioService.class.getResource("/META-INF/wsdl/ACCPJ_PagoServicioService.wsdl");
        WebServiceException e = null;
        if (PAGOSERVICIOSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ACCPJ_PagoServicioService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PAGOSERVICIOSERVICE_EXCEPTION = e;
    }

    public PagoServicioService() {
        super(__getWsdlLocation(), PAGOSERVICIOSERVICE_QNAME);
    }

    public PagoServicioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAGOSERVICIOSERVICE_QNAME, features);
    }

    public PagoServicioService(URL wsdlLocation) {
        super(wsdlLocation, PAGOSERVICIOSERVICE_QNAME);
    }

    public PagoServicioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAGOSERVICIOSERVICE_QNAME, features);
    }

    public PagoServicioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoServicioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PagoServicioPortType
     */
    @WebEndpoint(name = "PagoServicio_Port")
    public PagoServicioPortType getPagoServicioPort() {
        return super.getPort(new QName("http://grupobbva.com.pe/accpj/pagser/", "PagoServicio_Port"), PagoServicioPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoServicioPortType
     */
    @WebEndpoint(name = "PagoServicio_Port")
    public PagoServicioPortType getPagoServicioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://grupobbva.com.pe/accpj/pagser/", "PagoServicio_Port"), PagoServicioPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAGOSERVICIOSERVICE_EXCEPTION!= null) {
            throw PAGOSERVICIOSERVICE_EXCEPTION;
        }
        return PAGOSERVICIOSERVICE_WSDL_LOCATION;
    }

}
