//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package hiper.webservices.impl.hfirmas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import hiper.spring.beans.hfirmas.webservices.xsd.RpteActivacionBE;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numero_expediente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipo_operacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lista_representantes" type="{http://webservices.hfirmas.beans.spring.hiper/xsd}RpteActivacion_BE" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resultado_bastanteo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usuario" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numeroExpediente",
    "tipoOperacion",
    "listaRepresentantes",
    "resultadoBastanteo",
    "usuario"
})
@XmlRootElement(name = "activarPoderes")
public class ActivarPoderes {

    @XmlElement(name = "numero_expediente", nillable = true)
    protected String numeroExpediente;
    @XmlElement(name = "tipo_operacion", nillable = true)
    protected String tipoOperacion;
    @XmlElement(name = "lista_representantes", nillable = true)
    protected List<RpteActivacionBE> listaRepresentantes;
    @XmlElement(name = "resultado_bastanteo", nillable = true)
    protected String resultadoBastanteo;
    @XmlElement(nillable = true)
    protected String usuario;

    /**
     * Gets the value of the numeroExpediente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroExpediente() {
        return numeroExpediente;
    }

    /**
     * Sets the value of the numeroExpediente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroExpediente(String value) {
        this.numeroExpediente = value;
    }

    /**
     * Gets the value of the tipoOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoOperacion() {
        return tipoOperacion;
    }

    /**
     * Sets the value of the tipoOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoOperacion(String value) {
        this.tipoOperacion = value;
    }

    /**
     * Gets the value of the listaRepresentantes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaRepresentantes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaRepresentantes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpteActivacionBE }
     * 
     * 
     */
    public List<RpteActivacionBE> getListaRepresentantes() {
        if (listaRepresentantes == null) {
            listaRepresentantes = new ArrayList<RpteActivacionBE>();
        }
        return this.listaRepresentantes;
    }

    /**
     * Gets the value of the resultadoBastanteo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultadoBastanteo() {
        return resultadoBastanteo;
    }

    /**
     * Sets the value of the resultadoBastanteo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultadoBastanteo(String value) {
        this.resultadoBastanteo = value;
    }

    /**
     * Gets the value of the usuario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * Sets the value of the usuario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsuario(String value) {
        this.usuario = value;
    }

}
