//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package hiper.webservices.impl.hfirmas;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "WSServicioSFP", targetNamespace = "http://hfirmas.impl.webservices.hiper", wsdlLocation = "META-INF/wsdl/WSServicioSFP.wsdl")
public class WSServicioSFP
    extends Service
{

    private final static URL WSSERVICIOSFP_WSDL_LOCATION;
    private final static WebServiceException WSSERVICIOSFP_EXCEPTION;
    private final static QName WSSERVICIOSFP_QNAME = new QName("http://hfirmas.impl.webservices.hiper", "WSServicioSFP");

    static {
            WSSERVICIOSFP_WSDL_LOCATION = hiper.webservices.impl.hfirmas.WSServicioSFP.class.getResource("/META-INF/wsdl/WSServicioSFP.wsdl");
        WebServiceException e = null;
        if (WSSERVICIOSFP_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/WSServicioSFP.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        WSSERVICIOSFP_EXCEPTION = e;
    }

    public WSServicioSFP() {
        super(__getWsdlLocation(), WSSERVICIOSFP_QNAME);
    }

    public WSServicioSFP(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICIOSFP_QNAME, features);
    }

    public WSServicioSFP(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICIOSFP_QNAME);
    }

    public WSServicioSFP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICIOSFP_QNAME, features);
    }

    public WSServicioSFP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServicioSFP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSServicioSFPPortType
     */
    @WebEndpoint(name = "WSServicioSFPHttpSoap11Endpoint")
    public WSServicioSFPPortType getWSServicioSFPHttpSoap11Endpoint() {
        return super.getPort(new QName("http://hfirmas.impl.webservices.hiper", "WSServicioSFPHttpSoap11Endpoint"), WSServicioSFPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSServicioSFPPortType
     */
    @WebEndpoint(name = "WSServicioSFPHttpSoap11Endpoint")
    public WSServicioSFPPortType getWSServicioSFPHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://hfirmas.impl.webservices.hiper", "WSServicioSFPHttpSoap11Endpoint"), WSServicioSFPPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICIOSFP_EXCEPTION!= null) {
            throw WSSERVICIOSFP_EXCEPTION;
        }
        return WSSERVICIOSFP_WSDL_LOCATION;
    }

}
