//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package hiper.webservices.impl.hfirmas;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import hiper.spring.beans.hfirmas.webservices.xsd.ClientePJBE;
import hiper.spring.beans.hfirmas.webservices.xsd.EmpresaBE;
import hiper.spring.beans.hfirmas.webservices.xsd.PoderFirmaActivacion;
import hiper.spring.beans.hfirmas.webservices.xsd.RespuestaBE;
import hiper.spring.beans.hfirmas.webservices.xsd.RpteActivacionBE;
import hiper.spring.beans.hfirmas.webservices.xsd.TipoPJBE;

@WebService(name = "WSServicioSFPPortType", targetNamespace = "http://hfirmas.impl.webservices.hiper")
@XmlSeeAlso({
    hiper.spring.beans.hfirmas.webservices.xsd.ObjectFactory.class,
    hiper.webservices.impl.hfirmas.ObjectFactory.class
})
public interface WSServicioSFPPortType {


    /**
     * 
     * @param idCliente
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "urn:testRegistrarCliente")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "testRegistrarCliente", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.TestRegistrarCliente")
    @ResponseWrapper(localName = "testRegistrarClienteResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.TestRegistrarClienteResponse")
    public Boolean testRegistrarCliente(
        @WebParam(name = "IdCliente", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        Integer idCliente);

    /**
     * 
     * @param estado
     * @param codTipoPJ
     * @param indicadorOperacion
     * @param descripcionTipoPJ
     * @return
     *     returns java.util.List<hiper.spring.beans.hfirmas.webservices.xsd.TipoPJBE>
     */
    @WebMethod(action = "urn:obtenerTipoPJ")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "obtenerTipoPJ", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ObtenerTipoPJ")
    @ResponseWrapper(localName = "obtenerTipoPJResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ObtenerTipoPJResponse")
    public List<TipoPJBE> obtenerTipoPJ(
        @WebParam(name = "indicadorOperacion", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String indicadorOperacion,
        @WebParam(name = "codTipoPJ", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String codTipoPJ,
        @WebParam(name = "descripcionTipoPJ", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String descripcionTipoPJ,
        @WebParam(name = "estado", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String estado);

    /**
     * 
     * @param listaRepresentantes
     * @param codOperacion
     * @param codCliente
     * @param usrActivacion
     * @param idCliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:activarFirmasyPoderesEnHost")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "activarFirmasyPoderesEnHost", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ActivarFirmasyPoderesEnHost")
    @ResponseWrapper(localName = "activarFirmasyPoderesEnHostResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ActivarFirmasyPoderesEnHostResponse")
    public String activarFirmasyPoderesEnHost(
        @WebParam(name = "cod_operacion", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String codOperacion,
        @WebParam(name = "usr_activacion", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String usrActivacion,
        @WebParam(name = "cod_cliente", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String codCliente,
        @WebParam(name = "id_cliente", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        Integer idCliente,
        @WebParam(name = "lista_representantes", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        List<RpteActivacionBE> listaRepresentantes);

    /**
     * 
     * @param numeroDOI
     * @param listaEmpresasAbsorbidas
     * @param razonSocial
     * @param tipoDOI
     * @param codigoCentral
     * @return
     *     returns hiper.spring.beans.hfirmas.webservices.xsd.RespuestaBE
     */
    @WebMethod(action = "urn:fusionarEmpresas")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "fusionarEmpresas", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.FusionarEmpresas")
    @ResponseWrapper(localName = "fusionarEmpresasResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.FusionarEmpresasResponse")
    public RespuestaBE fusionarEmpresas(
        @WebParam(name = "tipo_DOI", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String tipoDOI,
        @WebParam(name = "numero_DOI", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String numeroDOI,
        @WebParam(name = "codigo_central", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String codigoCentral,
        @WebParam(name = "razon_social", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String razonSocial,
        @WebParam(name = "lista_empresas_absorbidas", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        List<String> listaEmpresasAbsorbidas);

    /**
     * 
     * @param nroDOI
     * @param razonSocial
     * @param tipoDOI
     * @param codigoCentral
     * @param listaEmpresas
     * @return
     *     returns hiper.spring.beans.hfirmas.webservices.xsd.RespuestaBE
     */
    @WebMethod(action = "urn:escindirEmpresas")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "escindirEmpresas", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.EscindirEmpresas")
    @ResponseWrapper(localName = "escindirEmpresasResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.EscindirEmpresasResponse")
    public RespuestaBE escindirEmpresas(
        @WebParam(name = "listaEmpresas", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        List<EmpresaBE> listaEmpresas,
        @WebParam(name = "codigoCentral", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String codigoCentral,
        @WebParam(name = "tipoDOI", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String tipoDOI,
        @WebParam(name = "nroDOI", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String nroDOI,
        @WebParam(name = "razonSocial", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String razonSocial);

    /**
     * 
     * @param idCliente
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(action = "urn:testRegistrarBastanteo")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "testRegistrarBastanteo", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.TestRegistrarBastanteo")
    @ResponseWrapper(localName = "testRegistrarBastanteoResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.TestRegistrarBastanteoResponse")
    public Boolean testRegistrarBastanteo(
        @WebParam(name = "IdCliente", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        Integer idCliente);

    /**
     * 
     * @param listaRepresentantes
     * @param resultadoBastanteo
     * @param numeroExpediente
     * @param tipoOperacion
     * @param usuario
     * @return
     *     returns hiper.spring.beans.hfirmas.webservices.xsd.PoderFirmaActivacion
     */
    @WebMethod(action = "urn:activarPoderes")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "activarPoderes", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ActivarPoderes")
    @ResponseWrapper(localName = "activarPoderesResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ActivarPoderesResponse")
    public PoderFirmaActivacion activarPoderes(
        @WebParam(name = "numero_expediente", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String numeroExpediente,
        @WebParam(name = "tipo_operacion", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String tipoOperacion,
        @WebParam(name = "lista_representantes", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        List<RpteActivacionBE> listaRepresentantes,
        @WebParam(name = "resultado_bastanteo", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String resultadoBastanteo,
        @WebParam(name = "usuario", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String usuario);

    /**
     * 
     * @param nroDOI
     * @param codCentralClte
     * @param version
     * @param tipoDOI
     * @return
     *     returns hiper.spring.beans.hfirmas.webservices.xsd.ClientePJBE
     */
    @WebMethod(action = "urn:obtenerPoderes")
    @WebResult(targetNamespace = "http://hfirmas.impl.webservices.hiper")
    @RequestWrapper(localName = "obtenerPoderes", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ObtenerPoderes")
    @ResponseWrapper(localName = "obtenerPoderesResponse", targetNamespace = "http://hfirmas.impl.webservices.hiper", className = "hiper.webservices.impl.hfirmas.ObtenerPoderesResponse")
    public ClientePJBE obtenerPoderes(
        @WebParam(name = "cod_central_clte", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String codCentralClte,
        @WebParam(name = "tipoDOI", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String tipoDOI,
        @WebParam(name = "nroDOI", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String nroDOI,
        @WebParam(name = "version", targetNamespace = "http://hfirmas.impl.webservices.hiper")
        String version);

}
