//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.ibm.bbva.reniec.message;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.ibm.bbva.reniec.header.RequestHeader;


/**
 * <p>Java class for consultaPorNombresRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="consultaPorNombresRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refRequestHeader" type="{http://pe.grupobbva.com/SIR/ents/header}RequestHeader"/>
 *         &lt;element name="refConsultaPorNombresRequest" type="{http://pe.grupobbva.com/SIR/ents/body/consultaPorNombres}ConsultaPorNombresRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultaPorNombresRequest", propOrder = {
    "refRequestHeader",
    "refConsultaPorNombresRequest"
})
public class ConsultaPorNombresRequest {

    @XmlElement(required = true)
    protected RequestHeader refRequestHeader;
    @XmlElement(required = true)
    protected com.ibm.bbva.reniec.consultapornombres.ConsultaPorNombresRequest refConsultaPorNombresRequest;

    /**
     * Gets the value of the refRequestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link RequestHeader }
     *     
     */
    public RequestHeader getRefRequestHeader() {
        return refRequestHeader;
    }

    /**
     * Sets the value of the refRequestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestHeader }
     *     
     */
    public void setRefRequestHeader(RequestHeader value) {
        this.refRequestHeader = value;
    }

    /**
     * Gets the value of the refConsultaPorNombresRequest property.
     * 
     * @return
     *     possible object is
     *     {@link com.ibm.bbva.reniec.consultapornombres.ConsultaPorNombresRequest }
     *     
     */
    public com.ibm.bbva.reniec.consultapornombres.ConsultaPorNombresRequest getRefConsultaPorNombresRequest() {
        return refConsultaPorNombresRequest;
    }

    /**
     * Sets the value of the refConsultaPorNombresRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.ibm.bbva.reniec.consultapornombres.ConsultaPorNombresRequest }
     *     
     */
    public void setRefConsultaPorNombresRequest(com.ibm.bbva.reniec.consultapornombres.ConsultaPorNombresRequest value) {
        this.refConsultaPorNombresRequest = value;
    }

}
