//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.com.grupobbva.accpj.pj;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctPJ complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctPJ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoDOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descTipoDOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numDOI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codigoCentral" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreRazonSocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechaConstitucion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codSector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descSector" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codActEconomica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descActEconomica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codDepartamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descDepartamento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codProvincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descProvincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="codDistrito" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descDistrito" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numCelular1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numCelular2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctPJ", propOrder = {
    "tipoDOI",
    "descTipoDOI",
    "numDOI",
    "codigoCentral",
    "nombreRazonSocial",
    "fechaConstitucion",
    "codSector",
    "descSector",
    "codActEconomica",
    "descActEconomica",
    "direccion",
    "codDepartamento",
    "descDepartamento",
    "codProvincia",
    "descProvincia",
    "codDistrito",
    "descDistrito",
    "numCelular1",
    "numCelular2",
    "email1",
    "email2"
})
public class CtPJ {

    @XmlElement(required = true)
    protected String tipoDOI;
    @XmlElement(required = true)
    protected String descTipoDOI;
    @XmlElement(required = true)
    protected String numDOI;
    @XmlElement(required = true)
    protected String codigoCentral;
    @XmlElement(required = true)
    protected String nombreRazonSocial;
    @XmlElement(required = true)
    protected String fechaConstitucion;
    @XmlElement(required = true)
    protected String codSector;
    @XmlElement(required = true)
    protected String descSector;
    @XmlElement(required = true)
    protected String codActEconomica;
    @XmlElement(required = true)
    protected String descActEconomica;
    @XmlElement(required = true)
    protected String direccion;
    @XmlElement(required = true)
    protected String codDepartamento;
    @XmlElement(required = true)
    protected String descDepartamento;
    @XmlElement(required = true)
    protected String codProvincia;
    @XmlElement(required = true)
    protected String descProvincia;
    @XmlElement(required = true)
    protected String codDistrito;
    @XmlElement(required = true)
    protected String descDistrito;
    @XmlElement(required = true)
    protected String numCelular1;
    @XmlElement(required = true)
    protected String numCelular2;
    @XmlElement(required = true)
    protected String email1;
    @XmlElement(required = true)
    protected String email2;

    /**
     * Gets the value of the tipoDOI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDOI() {
        return tipoDOI;
    }

    /**
     * Sets the value of the tipoDOI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDOI(String value) {
        this.tipoDOI = value;
    }

    /**
     * Gets the value of the descTipoDOI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescTipoDOI() {
        return descTipoDOI;
    }

    /**
     * Sets the value of the descTipoDOI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescTipoDOI(String value) {
        this.descTipoDOI = value;
    }

    /**
     * Gets the value of the numDOI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumDOI() {
        return numDOI;
    }

    /**
     * Sets the value of the numDOI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumDOI(String value) {
        this.numDOI = value;
    }

    /**
     * Gets the value of the codigoCentral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCentral() {
        return codigoCentral;
    }

    /**
     * Sets the value of the codigoCentral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCentral(String value) {
        this.codigoCentral = value;
    }

    /**
     * Gets the value of the nombreRazonSocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreRazonSocial() {
        return nombreRazonSocial;
    }

    /**
     * Sets the value of the nombreRazonSocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreRazonSocial(String value) {
        this.nombreRazonSocial = value;
    }

    /**
     * Gets the value of the fechaConstitucion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaConstitucion() {
        return fechaConstitucion;
    }

    /**
     * Sets the value of the fechaConstitucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaConstitucion(String value) {
        this.fechaConstitucion = value;
    }

    /**
     * Gets the value of the codSector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodSector() {
        return codSector;
    }

    /**
     * Sets the value of the codSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodSector(String value) {
        this.codSector = value;
    }

    /**
     * Gets the value of the descSector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescSector() {
        return descSector;
    }

    /**
     * Sets the value of the descSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescSector(String value) {
        this.descSector = value;
    }

    /**
     * Gets the value of the codActEconomica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodActEconomica() {
        return codActEconomica;
    }

    /**
     * Sets the value of the codActEconomica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodActEconomica(String value) {
        this.codActEconomica = value;
    }

    /**
     * Gets the value of the descActEconomica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescActEconomica() {
        return descActEconomica;
    }

    /**
     * Sets the value of the descActEconomica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescActEconomica(String value) {
        this.descActEconomica = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the codDepartamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodDepartamento() {
        return codDepartamento;
    }

    /**
     * Sets the value of the codDepartamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodDepartamento(String value) {
        this.codDepartamento = value;
    }

    /**
     * Gets the value of the descDepartamento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescDepartamento() {
        return descDepartamento;
    }

    /**
     * Sets the value of the descDepartamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescDepartamento(String value) {
        this.descDepartamento = value;
    }

    /**
     * Gets the value of the codProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodProvincia() {
        return codProvincia;
    }

    /**
     * Sets the value of the codProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodProvincia(String value) {
        this.codProvincia = value;
    }

    /**
     * Gets the value of the descProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescProvincia() {
        return descProvincia;
    }

    /**
     * Sets the value of the descProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescProvincia(String value) {
        this.descProvincia = value;
    }

    /**
     * Gets the value of the codDistrito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodDistrito() {
        return codDistrito;
    }

    /**
     * Sets the value of the codDistrito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodDistrito(String value) {
        this.codDistrito = value;
    }

    /**
     * Gets the value of the descDistrito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescDistrito() {
        return descDistrito;
    }

    /**
     * Sets the value of the descDistrito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescDistrito(String value) {
        this.descDistrito = value;
    }

    /**
     * Gets the value of the numCelular1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCelular1() {
        return numCelular1;
    }

    /**
     * Sets the value of the numCelular1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCelular1(String value) {
        this.numCelular1 = value;
    }

    /**
     * Gets the value of the numCelular2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumCelular2() {
        return numCelular2;
    }

    /**
     * Sets the value of the numCelular2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumCelular2(String value) {
        this.numCelular2 = value;
    }

    /**
     * Gets the value of the email1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail1() {
        return email1;
    }

    /**
     * Sets the value of the email1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail1(String value) {
        this.email1 = value;
    }

    /**
     * Gets the value of the email2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail2() {
        return email2;
    }

    /**
     * Sets the value of the email2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail2(String value) {
        this.email2 = value;
    }

}
