//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package hiper.spring.beans.hfirmas.webservices.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Poder_Firma_Activacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Poder_Firma_Activacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dsc_mensaje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="exito_activacion_poder" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lista_representantes_output" type="{http://webservices.hfirmas.beans.spring.hiper/xsd}RpteActivacion_BE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Poder_Firma_Activacion", propOrder = {
    "dscMensaje",
    "exitoActivacionPoder",
    "listaRepresentantesOutput"
})
public class PoderFirmaActivacion {

    @XmlElement(name = "dsc_mensaje", nillable = true)
    protected String dscMensaje;
    @XmlElement(name = "exito_activacion_poder")
    protected Boolean exitoActivacionPoder;
    @XmlElement(name = "lista_representantes_output", nillable = true)
    protected List<RpteActivacionBE> listaRepresentantesOutput;

    /**
     * Gets the value of the dscMensaje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDscMensaje() {
        return dscMensaje;
    }

    /**
     * Sets the value of the dscMensaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDscMensaje(String value) {
        this.dscMensaje = value;
    }

    /**
     * Gets the value of the exitoActivacionPoder property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExitoActivacionPoder() {
        return exitoActivacionPoder;
    }

    /**
     * Sets the value of the exitoActivacionPoder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExitoActivacionPoder(Boolean value) {
        this.exitoActivacionPoder = value;
    }

    /**
     * Gets the value of the listaRepresentantesOutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaRepresentantesOutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaRepresentantesOutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpteActivacionBE }
     * 
     * 
     */
    public List<RpteActivacionBE> getListaRepresentantesOutput() {
        if (listaRepresentantesOutput == null) {
            listaRepresentantesOutput = new ArrayList<RpteActivacionBE>();
        }
        return this.listaRepresentantesOutput;
    }

}
