//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.bbva.general.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "TablaGeneralService", targetNamespace = "http://service.general.bbva.com", wsdlLocation = "META-INF/wsdl/TablaGeneral.wsdl")
public class TablaGeneralService
    extends Service
{

    private final static URL TABLAGENERALSERVICE_WSDL_LOCATION;
    private final static WebServiceException TABLAGENERALSERVICE_EXCEPTION;
    private final static QName TABLAGENERALSERVICE_QNAME = new QName("http://service.general.bbva.com", "TablaGeneralService");

    static {
            TABLAGENERALSERVICE_WSDL_LOCATION = com.bbva.general.service.TablaGeneralService.class.getResource("/META-INF/wsdl/TablaGeneral.wsdl");
        WebServiceException e = null;
        if (TABLAGENERALSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/TablaGeneral.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TABLAGENERALSERVICE_EXCEPTION = e;
    }

    public TablaGeneralService() {
        super(__getWsdlLocation(), TABLAGENERALSERVICE_QNAME);
    }

    public TablaGeneralService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TABLAGENERALSERVICE_QNAME, features);
    }

    public TablaGeneralService(URL wsdlLocation) {
        super(wsdlLocation, TABLAGENERALSERVICE_QNAME);
    }

    public TablaGeneralService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TABLAGENERALSERVICE_QNAME, features);
    }

    public TablaGeneralService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TablaGeneralService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TablaGeneral
     */
    @WebEndpoint(name = "TablaGeneral")
    public TablaGeneral getTablaGeneral() {
        return super.getPort(new QName("http://service.general.bbva.com", "TablaGeneral"), TablaGeneral.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TablaGeneral
     */
    @WebEndpoint(name = "TablaGeneral")
    public TablaGeneral getTablaGeneral(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.general.bbva.com", "TablaGeneral"), TablaGeneral.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TABLAGENERALSERVICE_EXCEPTION!= null) {
            throw TABLAGENERALSERVICE_EXCEPTION;
        }
        return TABLAGENERALSERVICE_WSDL_LOCATION;
    }

}
