//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.service.business;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for empleadoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="empleadoVO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="apemat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="apepat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="correo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fecegr" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fecing" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="flagActivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="idNivelFk" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="idOficinaFk" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="idPerfilFk" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="idTipoCategoriaFk" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="nombres" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nombresCompletos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "empleadoVO", propOrder = {
    "apemat",
    "apepat",
    "codigo",
    "correo",
    "fecegr",
    "fecing",
    "flagActivo",
    "id",
    "idNivelFk",
    "idOficinaFk",
    "idPerfilFk",
    "idTipoCategoriaFk",
    "nombres",
    "nombresCompletos"
})
public class EmpleadoVO {

    protected String apemat;
    protected String apepat;
    protected String codigo;
    protected String correo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fecegr;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fecing;
    protected String flagActivo;
    protected Long id;
    protected Long idNivelFk;
    protected Long idOficinaFk;
    protected Long idPerfilFk;
    protected Long idTipoCategoriaFk;
    protected String nombres;
    protected String nombresCompletos;

    /**
     * Gets the value of the apemat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApemat() {
        return apemat;
    }

    /**
     * Sets the value of the apemat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApemat(String value) {
        this.apemat = value;
    }

    /**
     * Gets the value of the apepat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApepat() {
        return apepat;
    }

    /**
     * Sets the value of the apepat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApepat(String value) {
        this.apepat = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the correo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * Sets the value of the correo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreo(String value) {
        this.correo = value;
    }

    /**
     * Gets the value of the fecegr property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecegr() {
        return fecegr;
    }

    /**
     * Sets the value of the fecegr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecegr(XMLGregorianCalendar value) {
        this.fecegr = value;
    }

    /**
     * Gets the value of the fecing property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecing() {
        return fecing;
    }

    /**
     * Sets the value of the fecing property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecing(XMLGregorianCalendar value) {
        this.fecing = value;
    }

    /**
     * Gets the value of the flagActivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagActivo() {
        return flagActivo;
    }

    /**
     * Sets the value of the flagActivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagActivo(String value) {
        this.flagActivo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idNivelFk property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdNivelFk() {
        return idNivelFk;
    }

    /**
     * Sets the value of the idNivelFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdNivelFk(Long value) {
        this.idNivelFk = value;
    }

    /**
     * Gets the value of the idOficinaFk property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdOficinaFk() {
        return idOficinaFk;
    }

    /**
     * Sets the value of the idOficinaFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdOficinaFk(Long value) {
        this.idOficinaFk = value;
    }

    /**
     * Gets the value of the idPerfilFk property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdPerfilFk() {
        return idPerfilFk;
    }

    /**
     * Sets the value of the idPerfilFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdPerfilFk(Long value) {
        this.idPerfilFk = value;
    }

    /**
     * Gets the value of the idTipoCategoriaFk property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdTipoCategoriaFk() {
        return idTipoCategoriaFk;
    }

    /**
     * Sets the value of the idTipoCategoriaFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdTipoCategoriaFk(Long value) {
        this.idTipoCategoriaFk = value;
    }

    /**
     * Gets the value of the nombres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * Sets the value of the nombres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombres(String value) {
        this.nombres = value;
    }

    /**
     * Gets the value of the nombresCompletos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombresCompletos() {
        return nombresCompletos;
    }

    /**
     * Sets the value of the nombresCompletos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombresCompletos(String value) {
        this.nombresCompletos = value;
    }

}
