//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.service.business;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for perfilDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="perfilDTO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="descripcion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagAdministracion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagAsignacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagRegistraAyu" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagRegistraExp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idPerfil" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="listaCorreoJefes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nombrePerfil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "perfilDTO", propOrder = {
    "codigo",
    "descripcion",
    "flagAdministracion",
    "flagAsignacion",
    "flagRegistraAyu",
    "flagRegistraExp",
    "id",
    "idPerfil",
    "listaCorreoJefes",
    "nombrePerfil"
})
public class PerfilDTO {

    protected String codigo;
    protected String descripcion;
    protected String flagAdministracion;
    protected String flagAsignacion;
    protected String flagRegistraAyu;
    protected String flagRegistraExp;
    protected long id;
    protected long idPerfil;
    protected String listaCorreoJefes;
    protected String nombrePerfil;

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the descripcion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * Sets the value of the descripcion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion(String value) {
        this.descripcion = value;
    }

    /**
     * Gets the value of the flagAdministracion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagAdministracion() {
        return flagAdministracion;
    }

    /**
     * Sets the value of the flagAdministracion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagAdministracion(String value) {
        this.flagAdministracion = value;
    }

    /**
     * Gets the value of the flagAsignacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagAsignacion() {
        return flagAsignacion;
    }

    /**
     * Sets the value of the flagAsignacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagAsignacion(String value) {
        this.flagAsignacion = value;
    }

    /**
     * Gets the value of the flagRegistraAyu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagRegistraAyu() {
        return flagRegistraAyu;
    }

    /**
     * Sets the value of the flagRegistraAyu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagRegistraAyu(String value) {
        this.flagRegistraAyu = value;
    }

    /**
     * Gets the value of the flagRegistraExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagRegistraExp() {
        return flagRegistraExp;
    }

    /**
     * Sets the value of the flagRegistraExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagRegistraExp(String value) {
        this.flagRegistraExp = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the idPerfil property.
     * 
     */
    public long getIdPerfil() {
        return idPerfil;
    }

    /**
     * Sets the value of the idPerfil property.
     * 
     */
    public void setIdPerfil(long value) {
        this.idPerfil = value;
    }

    /**
     * Gets the value of the listaCorreoJefes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListaCorreoJefes() {
        return listaCorreoJefes;
    }

    /**
     * Sets the value of the listaCorreoJefes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListaCorreoJefes(String value) {
        this.listaCorreoJefes = value;
    }

    /**
     * Gets the value of the nombrePerfil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrePerfil() {
        return nombrePerfil;
    }

    /**
     * Sets the value of the nombrePerfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrePerfil(String value) {
        this.nombrePerfil = value;
    }

}
