//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package hiper.spring.beans.hfirmas.webservices.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Combinacion_BE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Combinacion_BE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="combinacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estado_desc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="listaFacultades" type="{http://webservices.hfirmas.beans.spring.hiper/xsd}Facultad_BE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Combinacion_BE", propOrder = {
    "combinacion",
    "estado",
    "estadoDesc",
    "listaFacultades"
})
public class CombinacionBE {

    @XmlElement(nillable = true)
    protected String combinacion;
    @XmlElement(nillable = true)
    protected String estado;
    @XmlElement(name = "estado_desc", nillable = true)
    protected String estadoDesc;
    @XmlElement(nillable = true)
    protected List<FacultadBE> listaFacultades;

    /**
     * Gets the value of the combinacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCombinacion() {
        return combinacion;
    }

    /**
     * Sets the value of the combinacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCombinacion(String value) {
        this.combinacion = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstado(String value) {
        this.estado = value;
    }

    /**
     * Gets the value of the estadoDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoDesc() {
        return estadoDesc;
    }

    /**
     * Sets the value of the estadoDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoDesc(String value) {
        this.estadoDesc = value;
    }

    /**
     * Gets the value of the listaFacultades property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaFacultades property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaFacultades().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FacultadBE }
     * 
     * 
     */
    public List<FacultadBE> getListaFacultades() {
        if (listaFacultades == null) {
            listaFacultades = new ArrayList<FacultadBE>();
        }
        return this.listaFacultades;
    }

}
