//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package pe.com.grupobbva.sce.qsp5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctBodyRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctBodyRs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apePaterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apeMaterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descPuesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="oficOperativa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descOficina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="perfil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="indTemporalidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="unidadGestora" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descBanca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aplicFacultades" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servicioA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servicioB" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctBodyRs", propOrder = {
    "nombre",
    "apePaterno",
    "apeMaterno",
    "descPuesto",
    "oficOperativa",
    "descOficina",
    "perfil",
    "indTemporalidad",
    "unidadGestora",
    "descBanca",
    "clio",
    "aplicFacultades",
    "servicioA",
    "servicioB"
})
public class CtBodyRs {

    @XmlElement(required = true)
    protected String nombre;
    @XmlElement(required = true)
    protected String apePaterno;
    @XmlElement(required = true)
    protected String apeMaterno;
    @XmlElement(required = true)
    protected String descPuesto;
    @XmlElement(required = true)
    protected String oficOperativa;
    @XmlElement(required = true)
    protected String descOficina;
    @XmlElement(required = true)
    protected String perfil;
    @XmlElement(required = true)
    protected String indTemporalidad;
    @XmlElement(required = true)
    protected String unidadGestora;
    @XmlElement(required = true)
    protected String descBanca;
    @XmlElement(required = true)
    protected String clio;
    @XmlElement(required = true)
    protected String aplicFacultades;
    @XmlElement(required = true)
    protected String servicioA;
    @XmlElement(required = true)
    protected String servicioB;

    /**
     * Gets the value of the nombre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * Sets the value of the nombre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombre(String value) {
        this.nombre = value;
    }

    /**
     * Gets the value of the apePaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApePaterno() {
        return apePaterno;
    }

    /**
     * Sets the value of the apePaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApePaterno(String value) {
        this.apePaterno = value;
    }

    /**
     * Gets the value of the apeMaterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApeMaterno() {
        return apeMaterno;
    }

    /**
     * Sets the value of the apeMaterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApeMaterno(String value) {
        this.apeMaterno = value;
    }

    /**
     * Gets the value of the descPuesto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescPuesto() {
        return descPuesto;
    }

    /**
     * Sets the value of the descPuesto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescPuesto(String value) {
        this.descPuesto = value;
    }

    /**
     * Gets the value of the oficOperativa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOficOperativa() {
        return oficOperativa;
    }

    /**
     * Sets the value of the oficOperativa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOficOperativa(String value) {
        this.oficOperativa = value;
    }

    /**
     * Gets the value of the descOficina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescOficina() {
        return descOficina;
    }

    /**
     * Sets the value of the descOficina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescOficina(String value) {
        this.descOficina = value;
    }

    /**
     * Gets the value of the perfil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerfil() {
        return perfil;
    }

    /**
     * Sets the value of the perfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerfil(String value) {
        this.perfil = value;
    }

    /**
     * Gets the value of the indTemporalidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndTemporalidad() {
        return indTemporalidad;
    }

    /**
     * Sets the value of the indTemporalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndTemporalidad(String value) {
        this.indTemporalidad = value;
    }

    /**
     * Gets the value of the unidadGestora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnidadGestora() {
        return unidadGestora;
    }

    /**
     * Sets the value of the unidadGestora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnidadGestora(String value) {
        this.unidadGestora = value;
    }

    /**
     * Gets the value of the descBanca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescBanca() {
        return descBanca;
    }

    /**
     * Sets the value of the descBanca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescBanca(String value) {
        this.descBanca = value;
    }

    /**
     * Gets the value of the clio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClio() {
        return clio;
    }

    /**
     * Sets the value of the clio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClio(String value) {
        this.clio = value;
    }

    /**
     * Gets the value of the aplicFacultades property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAplicFacultades() {
        return aplicFacultades;
    }

    /**
     * Sets the value of the aplicFacultades property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAplicFacultades(String value) {
        this.aplicFacultades = value;
    }

    /**
     * Gets the value of the servicioA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicioA() {
        return servicioA;
    }

    /**
     * Sets the value of the servicioA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicioA(String value) {
        this.servicioA = value;
    }

    /**
     * Gets the value of the servicioB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicioB() {
        return servicioB;
    }

    /**
     * Sets the value of the servicioB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicioB(String value) {
        this.servicioB = value;
    }

}
