package com.ibm.bbva.ctacte.bean;
// default package
// Generated 18/05/2012 01:52:30 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Documento generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_DOCUMENTO_CC", schema = "CONELE")
public class Documento implements java.io.Serializable,Comparable<Documento> {

	private static final long serialVersionUID = 1110199362992693954L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	private Integer id;
	
	@Column(name = "DESCRIPCION", length = 100)
	private String descripcion;
	
	@Column(name = "TIPO_DOCUMENTO", length = 20)
	private String tipoDocumento;
	
	@Column(name = "CODIGO_DOCUMENTO", length = 5)
	private String codigoDocumento;
	
	@Column(name = "TIPO_VISOR", length = 1)
	private String tipoVisor;
	
	@Column(name = "VIGENCIA_DIAS", precision = 22, scale = 0)
	private Integer vigenciaDias;
	
	@Column(name = "FLAG_VIGENCIA", length = 1)
	private String flagVigencia;
	
	@Column(name = "PESO_PROM_HOJA_KB", precision = 22, scale = 0)
	private Integer pesoPromHojaKB;
	
	@Column(name = "FLAG_NRO_PAGINA", length = 1)
	private String flagNroPagina;
	
	// [Begin]-[15.07.23]-[Cambio valores de los documentos (casos de negocio)]
	@Column(name = "FLAG_ULT_FECHA", length = 1)
	private String flagUltimaFecha;
	// [End]-[15.07.23]

	public Documento() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipoDocumento() {
		return tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getCodigoDocumento() {
		return codigoDocumento;
	}

	public void setCodigoDocumento(String codigoDocumento) {
		this.codigoDocumento = codigoDocumento;
	}

	public String getTipoVisor() {
		return tipoVisor;
	}

	public void setTipoVisor(String tipoVisor) {
		this.tipoVisor = tipoVisor;
	}

	public Integer getVigenciaDias() {
		return vigenciaDias;
	}

	public void setVigenciaDias(Integer vigenciaDias) {
		this.vigenciaDias = vigenciaDias;
	}

	public String getFlagVigencia() {
		return flagVigencia;
	}

	public void setFlagVigencia(String flagVigencia) {
		this.flagVigencia = flagVigencia;
	}

	public Integer getPesoPromHojaKB() {
		return pesoPromHojaKB;
	}

	public void setPesoPromHojaKB(Integer pesoPromHojaKB) {
		this.pesoPromHojaKB = pesoPromHojaKB;
	}

	public String getFlagNroPagina() {
		return flagNroPagina;
	}

	public void setFlagNroPagina(String flagNroPagina) {
		this.flagNroPagina = flagNroPagina;
	}

	// [Begin]-[15.07.23]-[Cambio valores de los documentos (casos de negocio)]
	public String getFlagUltimaFecha() {
		return flagUltimaFecha;
	}

	public void setFlagUltimaFecha(String flagUltimaFecha) {
		this.flagUltimaFecha = flagUltimaFecha;
	}
	// [End]-[15.07.23]

	public int compareTo(Documento o) {
		//+POR SOLICITUD BBVA+//+POR SOLICITUD BBVA+System.out..println(" o : "+o);
		//+POR SOLICITUD BBVA+//+POR SOLICITUD BBVA+System.out..println(" this : "+this);
		
		return this.getDescripcion().compareTo(o.getDescripcion());
	}
}
