package com.ibm.bbva.ctacte.bean;
// default package
// Generated 17/05/2012 06:04:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GuiaDocumentId generated by hbm2java
 */
@Embeddable
public class GuiaDocumentId implements java.io.Serializable {

	private static final long serialVersionUID = 2241722791961638675L;

	@Column(name = "ID_OPERACION_FK", nullable = false, precision = 22, scale = 0)
	private Integer idOperacionFk;
	
	@Column(name = "ID_DOCUMENTO_FK", nullable = false, precision = 22, scale = 0)
	private Integer idDocumentoFk;
	
	@Column(name="ID_CASO_NEGOCIO_FK", nullable=false, precision=10, scale = 0)
	private Integer idCasoNegocioFk;
	
	@Column(name = "COD_TIPO_PJ", nullable = false, length = 2)
	private String codTipoPj;

	public GuiaDocumentId() {
	}

	public Integer getIdOperacionFk() {
		return idOperacionFk;
	}

	public void setIdOperacionFk(Integer idOperacionFk) {
		this.idOperacionFk = idOperacionFk;
	}

	public Integer getIdDocumentoFk() {
		return idDocumentoFk;
	}

	public void setIdDocumentoFk(Integer idDocumentoFk) {
		this.idDocumentoFk = idDocumentoFk;
	}

	public Integer getIdCasoNegocioFk() {
		return idCasoNegocioFk;
	}

	public void setIdCasoNegocioFk(Integer idCasoNegocioFk) {
		this.idCasoNegocioFk = idCasoNegocioFk;
	}

	public String getCodTipoPj() {
		return codTipoPj;
	}

	public void setCodTipoPj(String codTipoPj) {
		this.codTipoPj = codTipoPj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GuiaDocumentId))
			return false;
		GuiaDocumentId castOther = (GuiaDocumentId) other;

		return ((this.getIdOperacionFk() == castOther.getIdOperacionFk()) || (this
				.getIdOperacionFk() != null
				&& castOther.getIdOperacionFk() != null && this
				.getIdOperacionFk().equals(castOther.getIdOperacionFk())))
				&& ((this.getIdDocumentoFk() == castOther.getIdDocumentoFk()) || (this
						.getIdDocumentoFk() != null
						&& castOther.getIdDocumentoFk() != null && this
						.getIdDocumentoFk()
						.equals(castOther.getIdDocumentoFk())))
				&& ((this.getIdCasoNegocioFk() == castOther.getIdCasoNegocioFk()) || (this
						.getIdCasoNegocioFk() != null
						&& castOther.getIdCasoNegocioFk() != null && this
						.getIdCasoNegocioFk()
						.equals(castOther.getIdCasoNegocioFk())))
				&& ((this.getCodTipoPj() == castOther.getCodTipoPj()) || (this
						.getCodTipoPj() != null
						&& castOther.getCodTipoPj() != null && this
						.getCodTipoPj().equals(castOther.getCodTipoPj())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdOperacionFk() == null ? 0 : this.getIdOperacionFk()
						.hashCode());
		result = 37
				* result
				+ (getIdDocumentoFk() == null ? 0 : this.getIdDocumentoFk()
						.hashCode());
		result = 37
				* result
				+ (getIdCasoNegocioFk() == null ? 0 : this.getIdCasoNegocioFk()
						.hashCode());
		result = 37 * result
				+ (getCodTipoPj() == null ? 0 : this.getCodTipoPj().hashCode());
		return result;
	}

}
