package com.ibm.bbva.ctacte.bean;
// default package
// Generated 17/05/2012 06:04:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GuiaDocument generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_GUIA_DOCUMENT_CC", schema = "CONELE")
public class GuiaDocument implements java.io.Serializable {

	private static final long serialVersionUID = 2398432024380165737L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idOperacionFk", column = @Column(name = "ID_OPERACION_FK", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idDocumentoFk", column = @Column(name = "ID_DOCUMENTO_FK", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "idCasoNegocioFk", column = @Column(name = "ID_CASO_NEGOCIO_FK", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "codTipoPj", column = @Column(name = "COD_TIPO_PJ", nullable = false, length = 2)) })
	private GuiaDocumentId id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_DOCUMENTO_FK", nullable = false, insertable = false, updatable = false)
	private Documento documento;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PRODUCTO_FK")
	private Producto producto;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_OPERACION_FK", nullable = false, insertable = false, updatable = false)
	private Operacion operacion;
	
	@ManyToOne
	@JoinColumn(name="ID_CASO_NEGOCIO_FK", nullable=false, insertable=false, updatable=false)
	private CasoNegocio casoNegocio;
	
	@Column(name = "FLAG_OBLIGATORIO", length = 1)
	private String flagObligatorio;
	
	@Column(name = "FLAG_REEMPLAZABLE", length = 1)
	private String flagReemplazable;
	
	@Column(name = "FLAG_CADUCA", length = 1)
	private String flagCaduca;
	
	@Column(name = "FLAG_REQ_ESCANEO", length = 1)
	private String flagReqEscaneo;
	
	@Column(name = "DES_TIPO_PJ", nullable = false, length = 30)
	private String desTipoPj;

	public GuiaDocument() {
	}

	public GuiaDocumentId getId() {
		return id;
	}

	public void setId(GuiaDocumentId id) {
		this.id = id;
	}

	public Documento getDocumento() {
		return documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Producto getProducto() {
		return producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Operacion getOperacion() {
		return operacion;
	}

	public void setOperacion(Operacion operacion) {
		this.operacion = operacion;
	}

	public CasoNegocio getCasoNegocio() {
		return casoNegocio;
	}

	public void setCasoNegocio(CasoNegocio casoNegocio) {
		this.casoNegocio = casoNegocio;
	}

	public String getFlagObligatorio() {
		return flagObligatorio;
	}

	public void setFlagObligatorio(String flagObligatorio) {
		this.flagObligatorio = flagObligatorio;
	}

	public String getFlagReemplazable() {
		return flagReemplazable;
	}

	public void setFlagReemplazable(String flagReemplazable) {
		this.flagReemplazable = flagReemplazable;
	}

	public String getFlagCaduca() {
		return flagCaduca;
	}

	public void setFlagCaduca(String flagCaduca) {
		this.flagCaduca = flagCaduca;
	}

	public String getFlagReqEscaneo() {
		return flagReqEscaneo;
	}

	public void setFlagReqEscaneo(String flagReqEscaneo) {
		this.flagReqEscaneo = flagReqEscaneo;
	}

	public String getDesTipoPj() {
		return desTipoPj;
	}

	public void setDesTipoPj(String desTipoPj) {
		this.desTipoPj = desTipoPj;
	}

}
