package com.ibm.bbva.ctacte.bean;

// default package
// Generated 09/08/2012 11:20:03 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_HORARIO", schema = "CONELE")
public class Horario implements java.io.Serializable {

	private static final long serialVersionUID = 6360424195407489925L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	private Integer id;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DIA_INICIO", length = 7)
	private Date diaInicio;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DIA_FIN", length = 7)
	private Date diaFin;
	
	@Column(name = "DOM", precision = 22, scale = 0)
	private Integer dom;
	
	@Column(name = "LUN", precision = 22, scale = 0)
	private Integer lun;
	
	@Column(name = "MAR", precision = 22, scale = 0)
	private Integer mar;
	
	@Column(name = "MIE", precision = 22, scale = 0)
	private Integer mie;
	
	@Column(name = "JUE", precision = 22, scale = 0)
	private Integer jue;
	
	@Column(name = "VIE", precision = 22, scale = 0)
	private Integer vie;
	
	@Column(name = "SAB", precision = 22, scale = 0)
	private Integer sab;
	
	@Column(name = "EXCEPCION", length = 1)
	private String excepcion;
	
	@Column(name = "ACTIVO", length = 1)
	private String activo;
	
	@Column(name = "HORA_INICIO", length = 5)
	private String horaInicio;
	
	@Column(name = "HORA_FIN", length = 5)
	private String horaFin;
	
	@Column(name = "TODO_DIA", length = 1)
	private String todoDia;

	public Horario() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDiaInicio() {
		return diaInicio;
	}

	public void setDiaInicio(Date diaInicio) {
		this.diaInicio = diaInicio;
	}

	public Date getDiaFin() {
		return diaFin;
	}

	public void setDiaFin(Date diaFin) {
		this.diaFin = diaFin;
	}

	public Integer getDom() {
		return dom;
	}

	public void setDom(Integer dom) {
		this.dom = dom;
	}

	public Integer getLun() {
		return lun;
	}

	public void setLun(Integer lun) {
		this.lun = lun;
	}

	public Integer getMar() {
		return mar;
	}

	public void setMar(Integer mar) {
		this.mar = mar;
	}

	public Integer getMie() {
		return mie;
	}

	public void setMie(Integer mie) {
		this.mie = mie;
	}

	public Integer getJue() {
		return jue;
	}

	public void setJue(Integer jue) {
		this.jue = jue;
	}

	public Integer getVie() {
		return vie;
	}

	public void setVie(Integer vie) {
		this.vie = vie;
	}

	public Integer getSab() {
		return sab;
	}

	public void setSab(Integer sab) {
		this.sab = sab;
	}

	public String getExcepcion() {
		return excepcion;
	}

	public void setExcepcion(String excepcion) {
		this.excepcion = excepcion;
	}

	public String getActivo() {
		return activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public String getHoraInicio() {
		return horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	public String getHoraFin() {
		return horaFin;
	}

	public void setHoraFin(String horaFin) {
		this.horaFin = horaFin;
	}

	public String getTodoDia() {
		return todoDia;
	}

	public void setTodoDia(String todoDia) {
		this.todoDia = todoDia;
	}

}
