package com.ibm.bbva.ctacte.bean;
// default package
// Generated 14/05/2012 10:37:52 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Oficina generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_OFICINA", schema = "CONELE")
public class Oficina implements java.io.Serializable {

	private static final long serialVersionUID = 5558179890477520258L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TERRITORIO_FK", nullable = false)
	private Territorio territorio;
	
	@Column(name = "CODIGO", nullable = false, length = 5)
	private String codigo;
	
	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	private String descripcion;
	
	@Column(name = "UBICACION", nullable = false, length = 100)
	private String ubicacion;
	
	@Column(name = "FLAG_AREA_RIESGO", nullable = false, length = 1)
	private String flagAreaRiesgo;
	
	@Column(name = "MONTO_TOPE", nullable = false)
	private Float montoTope;
	
	@Column(name = "FLAG_DESPLAZADA", nullable = false, length = 1)
	private String flagDesplazada;
	
	@Column(name = "FLAG_ESCANEO_WEB", nullable = false, length = 1)
	private String flagEscaneoWeb;
	
	public Oficina() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Territorio getTerritorio() {
		return territorio;
	}

	public void setTerritorio(Territorio territorio) {
		this.territorio = territorio;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getUbicacion() {
		return ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getFlagAreaRiesgo() {
		return flagAreaRiesgo;
	}

	public void setFlagAreaRiesgo(String flagAreaRiesgo) {
		this.flagAreaRiesgo = flagAreaRiesgo;
	}

	public Float getMontoTope() {
		return montoTope;
	}

	public void setMontoTope(Float montoTope) {
		this.montoTope = montoTope;
	}

	public String getFlagDesplazada() {
		return flagDesplazada;
	}

	public void setFlagDesplazada(String flagDesplazada) {
		this.flagDesplazada = flagDesplazada;
	}

	public String getFlagEscaneoWeb() {
		return flagEscaneoWeb;
	}

	public void setFlagEscaneoWeb(String flagEscaneoWeb) {
		this.flagEscaneoWeb = flagEscaneoWeb;
	}

}
