package com.ibm.bbva.ctacte.bean;
// default package
// Generated 17/05/2012 03:38:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Participe generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_PARTICIPE_CC", schema = "CONELE")
public class Participe implements java.io.Serializable {

	private static final long serialVersionUID = 8281410462985204746L;

	@Id
	@SequenceGenerator(name = "seqParticipe", sequenceName = "SEQ_CE_IBM_PARTICIPE_CC", allocationSize=1, schema = "CONELE")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="seqParticipe")
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CLIENTE_FK")
	private Cliente cliente;
	
	@Column(name = "CODIGO_CENTRAL", length = 15)
	private String codigoCentral;
	
	@Column(name = "TIPO_DOI", length = 1)
	private String tipoDoi;
	
	@Column(name = "NUMERO_DOI", length = 11)
	private String numeroDoi;
	
	@Column(name = "NOMBRE", length = 20)
	private String nombre;
	
	@Column(name = "APELLIDO_PATERNO", length = 20)
	private String apellidoPaterno;
	
	@Column(name = "APELLIDO_MATERNO", length = 20)
	private String apellidoMaterno;
	
	@Column(name = "NUMERO_CUENTA", length = 15)
	private String numeroCuenta;
	
	@Column(name = "FLAG_FIRMA_ASOCIADA", length = 1)
	private String flagFirmaAsociada;
	
	@Column(name = "FLAG_FIRMA_ACTIVA", length = 1)
	private String flagFirmaActiva;
	
	@Column(name = "FLAG_INDICADOR_FIRMA", length = 1)
	private String flagIndicadorFirma;
	
	@Column(name = "TIPO_DOI_DES", length = 20)
	private String tipoDoiDes;
	
	@Column(name = "DIRECCION", length = 60)
	private String direccion;
	
	@Column(name = "UBICACION", length = 60)
	private String ubicacion;
	
	@Column(name = "DEPARTAMENTO_COD", length = 2)
	private String departamentoCod;
	
	@Column(name = "DEPARTAMENTO_DES", length = 30)
	private String departamentoDes;
	
	@Column(name = "PROVINCIA_COD", length = 2)
	private String provinciaCod;
	
	@Column(name = "PROVINCIA_DES", length = 30)
	private String provinciaDes;
	
	@Column(name = "DISTRITO_COD", length = 3)
	private String distritoCod;
	
	@Column(name = "DISTRITO_DES", length = 30)
	private String distritoDes;
	
	@Column(name = "INDICADOR_FIRMA", length = 1)
	private String indicadorFirma;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_SERIALIZACION", length = 7)
	private Date fechaSerializacion;
	
	@Column(name = "NIVEL_INTERVENCION", length = 1)
	private String nivelIntervencion;
	
	@Column(name = "SECUENCIA_INTERVENCION", length = 2)
	private String secuenciaIntervencion;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_CUENTA_FK")
	private Cuenta cuenta;
	
	public Participe() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getCodigoCentral() {
		return codigoCentral;
	}

	public void setCodigoCentral(String codigoCentral) {
		this.codigoCentral = codigoCentral;
	}

	public String getTipoDoi() {
		return tipoDoi;
	}

	public void setTipoDoi(String tipoDoi) {
		this.tipoDoi = tipoDoi;
	}

	public String getNumeroDoi() {
		return numeroDoi;
	}

	public void setNumeroDoi(String numeroDoi) {
		this.numeroDoi = numeroDoi;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidoPaterno() {
		return apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getNumeroCuenta() {
		return numeroCuenta;
	}

	public void setNumeroCuenta(String numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public String getFlagFirmaAsociada() {
		return flagFirmaAsociada;
	}

	public void setFlagFirmaAsociada(String flagFirmaAsociada) {
		this.flagFirmaAsociada = flagFirmaAsociada;
	}

	public String getFlagFirmaActiva() {
		return flagFirmaActiva;
	}

	public void setFlagFirmaActiva(String flagFirmaActiva) {
		this.flagFirmaActiva = flagFirmaActiva;
	}

	public String getFlagIndicadorFirma() {
		return flagIndicadorFirma;
	}

	public void setFlagIndicadorFirma(String flagIndicadorFirma) {
		this.flagIndicadorFirma = flagIndicadorFirma;
	}

	public String getTipoDoiDes() {
		return tipoDoiDes;
	}

	public void setTipoDoiDes(String tipoDoiDes) {
		this.tipoDoiDes = tipoDoiDes;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getUbicacion() {
		return ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getDepartamentoCod() {
		return departamentoCod;
	}

	public void setDepartamentoCod(String departamentoCod) {
		this.departamentoCod = departamentoCod;
	}

	public String getDepartamentoDes() {
		return departamentoDes;
	}

	public void setDepartamentoDes(String departamentoDes) {
		this.departamentoDes = departamentoDes;
	}

	public String getProvinciaCod() {
		return provinciaCod;
	}

	public void setProvinciaCod(String provinciaCod) {
		this.provinciaCod = provinciaCod;
	}

	public String getProvinciaDes() {
		return provinciaDes;
	}

	public void setProvinciaDes(String provinciaDes) {
		this.provinciaDes = provinciaDes;
	}

	public String getDistritoCod() {
		return distritoCod;
	}

	public void setDistritoCod(String distritoCod) {
		this.distritoCod = distritoCod;
	}

	public String getDistritoDes() {
		return distritoDes;
	}

	public void setDistritoDes(String distritoDes) {
		this.distritoDes = distritoDes;
	}

	public String getIndicadorFirma() {
		return indicadorFirma;
	}

	public void setIndicadorFirma(String indicadorFirma) {
		this.indicadorFirma = indicadorFirma;
	}

	public Date getFechaSerializacion() {
		return fechaSerializacion;
	}

	public void setFechaSerializacion(Date fechaSerializacion) {
		this.fechaSerializacion = fechaSerializacion;
	}

	public String getNivelIntervencion() {
		return nivelIntervencion;
	}

	public void setNivelIntervencion(String nivelIntervencion) {
		this.nivelIntervencion = nivelIntervencion;
	}

	public String getSecuenciaIntervencion() {
		return secuenciaIntervencion;
	}

	public void setSecuenciaIntervencion(String secuenciaIntervencion) {
		this.secuenciaIntervencion = secuenciaIntervencion;
	}

	public Cuenta getCuenta() {
		return cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}
	
}
