package com.ibm.bbva.ctacte.bean;
// default package
// Generated 15/05/2012 05:34:58 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tarea generated by hbm2java
 */
@Entity
@Table(name = "TBL_CE_IBM_TAREA_CC", schema = "CONELE")
public class Tarea implements java.io.Serializable {

	private static final long serialVersionUID = 1377216894906575436L;

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	private Integer id;
	
	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	private String descripcion;
	
	@Column(name = "VERDE_MINUTOS", precision = 7, scale = 0)
	private Integer verdeMinutos;
	
	@Column(name = "AMARILLO_MINUTOS", precision = 7, scale = 0)
	private Integer amarilloMinutos;
	
	@Column(name = "NOMBRE_PAGINA", nullable = false, length = 70)
	private String nombrePagina;

	public Tarea() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getVerdeMinutos() {
		return verdeMinutos;
	}

	public void setVerdeMinutos(Integer verdeMinutos) {
		this.verdeMinutos = verdeMinutos;
	}

	public Integer getAmarilloMinutos() {
		return amarilloMinutos;
	}

	public void setAmarilloMinutos(Integer amarilloMinutos) {
		this.amarilloMinutos = amarilloMinutos;
	}

	public String getNombrePagina() {
		return nombrePagina;
	}

	public void setNombrePagina(String nombrePagina) {
		this.nombrePagina = nombrePagina;
	}

}
