//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package com.bbva.general.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.bbva.general.entities.Ubigeo;


/**
 * <p>Java class for ArrayOf_tns2_nillable_Ubigeo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOf_tns2_nillable_Ubigeo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ubigeo" type="{http://entities.general.bbva.com}Ubigeo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOf_tns2_nillable_Ubigeo", propOrder = {
    "ubigeo"
})
public class ArrayOfTns2NillableUbigeo {

    @XmlElement(name = "Ubigeo", nillable = true)
    protected List<Ubigeo> ubigeo;

    /**
     * Gets the value of the ubigeo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ubigeo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUbigeo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ubigeo }
     * 
     * 
     */
    public List<Ubigeo> getUbigeo() {
        if (ubigeo == null) {
            ubigeo = new ArrayList<Ubigeo>();
        }
        return this.ubigeo;
    }

}
