//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.cm.iice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ContentServiceImpl", targetNamespace = "http://impl.service.cm.bbva.ibm.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContentServiceImpl {


    /**
     * 
     * @param documento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "insert_PID", action = "insert_PID")
    @WebResult(name = "insert_PIDReturn", targetNamespace = "")
    @RequestWrapper(localName = "insert_PID", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.InsertPID")
    @ResponseWrapper(localName = "insert_PIDResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.InsertPIDResponse")
    public String insertPID(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param documentos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "insertAll")
    @WebResult(name = "insertAllReturn", targetNamespace = "")
    @RequestWrapper(localName = "insertAll", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.InsertAll")
    @ResponseWrapper(localName = "insertAllResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.InsertAllResponse")
    public String insertAll(
        @WebParam(name = "documentos", targetNamespace = "")
        ArrayOf1659910637NillableDocumento documentos);

    /**
     * 
     * @param documento
     * @return
     *     returns com.ibm.bbva.cm.iice.service.ArrayOf1659910637NillableDocumento
     */
    @WebMethod(action = "findAll")
    @WebResult(name = "findAllReturn", targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.FindAllResponse")
    public ArrayOf1659910637NillableDocumento findAll(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param documento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "update")
    @WebResult(name = "updateReturn", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.UpdateResponse")
    public String update(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param tipoDoc
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "actualizarTipoDoc")
    @WebResult(name = "actualizarTipoDocReturn", targetNamespace = "")
    @RequestWrapper(localName = "actualizarTipoDoc", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.ActualizarTipoDoc")
    @ResponseWrapper(localName = "actualizarTipoDocResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.ActualizarTipoDocResponse")
    public String actualizarTipoDoc(
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "tipoDoc", targetNamespace = "")
        String tipoDoc);

    /**
     * 
     * @param documento
     * @param mimeType
     * @return
     *     returns com.ibm.bbva.cm.iice.service.Documento
     */
    @WebMethod(action = "findAsImage")
    @WebResult(name = "findAsImageReturn", targetNamespace = "")
    @RequestWrapper(localName = "findAsImage", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.FindAsImage")
    @ResponseWrapper(localName = "findAsImageResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.FindAsImageResponse")
    public Documento findAsImage(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento,
        @WebParam(name = "mimeType", targetNamespace = "")
        String mimeType);

    /**
     * 
     * @param documento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "delete")
    @WebResult(name = "deleteReturn", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.DeleteResponse")
    public String delete(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param documentos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "deleteAll")
    @WebResult(name = "deleteAllReturn", targetNamespace = "")
    @RequestWrapper(localName = "deleteAll", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.DeleteAll")
    @ResponseWrapper(localName = "deleteAllResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.DeleteAllResponse")
    public String deleteAll(
        @WebParam(name = "documentos", targetNamespace = "")
        ArrayOf1659910637NillableDocumento documentos);

    /**
     * 
     * @param documento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "insert")
    @WebResult(name = "insertReturn", targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.InsertResponse")
    public String insert(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

    /**
     * 
     * @param documento
     * @return
     *     returns com.ibm.bbva.cm.iice.service.Documento
     */
    @WebMethod(action = "find")
    @WebResult(name = "findReturn", targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://impl.service.cm.bbva.ibm.com", className = "com.ibm.bbva.cm.iice.service.FindResponse")
    public Documento find(
        @WebParam(name = "documento", targetNamespace = "")
        Documento documento);

}
