//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.bbva.content.manager.ws.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ContentManagerWS", targetNamespace = "http://www.example.org/ContentManagerWS/", wsdlLocation = "META-INF/wsdl/ContentManagerWS.wsdl")
public class ContentManagerWS_Service
    extends Service
{

    private final static URL CONTENTMANAGERWS_WSDL_LOCATION;
    private final static WebServiceException CONTENTMANAGERWS_EXCEPTION;
    private final static QName CONTENTMANAGERWS_QNAME = new QName("http://www.example.org/ContentManagerWS/", "ContentManagerWS");

    static {
            CONTENTMANAGERWS_WSDL_LOCATION = com.bbva.content.manager.ws.client.ContentManagerWS_Service.class.getResource("/META-INF/wsdl/ContentManagerWS.wsdl");
        WebServiceException e = null;
        if (CONTENTMANAGERWS_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ContentManagerWS.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CONTENTMANAGERWS_EXCEPTION = e;
    }

    public ContentManagerWS_Service() {
        super(__getWsdlLocation(), CONTENTMANAGERWS_QNAME);
    }

//    public ContentManagerWS_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), CONTENTMANAGERWS_QNAME, features);
//    }

    public ContentManagerWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CONTENTMANAGERWS_QNAME);
    }

//    public ContentManagerWS_Service(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, CONTENTMANAGERWS_QNAME, features);
//    }

    public ContentManagerWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

//    public ContentManagerWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns ContentManagerWS
     */
    @WebEndpoint(name = "ContentManagerWSSOAP")
    public ContentManagerWS getContentManagerWSSOAP() {
        return super.getPort(new QName("http://www.example.org/ContentManagerWS/", "ContentManagerWSSOAP"), ContentManagerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContentManagerWS
     */
    @WebEndpoint(name = "ContentManagerWSSOAP")
    public ContentManagerWS getContentManagerWSSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/ContentManagerWS/", "ContentManagerWSSOAP"), ContentManagerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTENTMANAGERWS_EXCEPTION!= null) {
            throw CONTENTMANAGERWS_EXCEPTION;
        }
        return CONTENTMANAGERWS_WSDL_LOCATION;
    }

}
