//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.bbva.content.manager.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "ContentManagerWS", targetNamespace = "http://www.example.org/ContentManagerWS/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContentManagerWS {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.bbva.content.manager.ws.client.ObtenerResponse
     */
    @WebMethod(action = "http://www.example.org/ContentManagerWS/obtener")
    @WebResult(name = "obtenerResponse", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
    public ObtenerResponse obtener(
        @WebParam(name = "obtenerRequest", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
        ObtenerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.bbva.content.manager.ws.client.InsertarResponse
     */
    @WebMethod(action = "http://www.example.org/ContentManagerWS/insertar")
    @WebResult(name = "insertarResponse", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
    public InsertarResponse insertar(
        @WebParam(name = "insertarRequest", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
        InsertarRequest parameters);

//    /**
//     * 
//     * @param parameters
//     * @return
//     *     returns com.bbva.content.manager.ws.client.ActualizarResponse
//     */
//    @WebMethod(action = "http://www.example.org/ContentManagerWS/actualizar")
//    @WebResult(name = "actualizarResponse", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
//    public ActualizarResponse actualizar(
//        @WebParam(name = "actualizarRequest", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
//        ActualizarRequest parameters);
//
//    /**
//     * 
//     * @param parameters
//     * @return
//     *     returns com.bbva.content.manager.ws.client.EliminarResponse
//     */
//    @WebMethod(action = "http://www.example.org/ContentManagerWS/eliminar")
//    @WebResult(name = "eliminarResponse", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
//    public EliminarResponse eliminar(
//        @WebParam(name = "eliminarRequest", targetNamespace = "http://www.example.org/ContentManagerWS/", partName = "parameters")
//        EliminarRequest parameters);

}
