
package pe.bbvacontinental.medios.gestiondemanda.contentmanagerws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContentManagerWSPortType", targetNamespace = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContentManagerWSPortType {


    /**
     * 
     * @param request
     * @return
     *     returns pe.bbvacontinental.medios.gestiondemanda.contentmanagerws.ws.InsertarDocResponse
     */
    @WebMethod(action = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/insertarDoc")
    @WebResult(name = "insertarDocResponse", targetNamespace = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/ws/types", partName = "response")
    public InsertarDocResponse insertarDoc(
        @WebParam(name = "insertarDocRequest", targetNamespace = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/ws/types", partName = "request")
        InsertarDocRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns pe.bbvacontinental.medios.gestiondemanda.contentmanagerws.ws.ObtenerDocResponse
     */
    @WebMethod(action = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/obtenerDoc")
    @WebResult(name = "obtenerDocResponse", targetNamespace = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/ws/types", partName = "response")
    public ObtenerDocResponse obtenerDoc(
        @WebParam(name = "obtenerDocRequest", targetNamespace = "http://bbvacontinental.pe/medios/gestiondemanda/contentmanagerws/ws/types", partName = "request")
        ObtenerDocRequest request);

}
