spool 002_update_data.log

DELETE FROM CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC WHERE ID IN (58, 62);
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (58, 'CARGA','empleados.frecuenciaDias','1');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (59, 'CARGA','empleados.horaEjecucion','23:00:00');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (60, 'CARGA','empleados.ldapCargaActivo','1');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (61,'CONF','paginaInicioCtaCte','https://espper.peru.igrupobbva/continental18/BBVA_CTACTE_GUI');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (62,'CONF','intentosWSCtaCte','20');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (63,'LOG','log4j.appender.archivoLDAPCarga','org.apache.log4j.RollingFileAppender');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (64,'LOG','log4j.appender.archivoLDAPCarga.file','/pr/conele/logs/LDAPCarga.log');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (65,'LOG','log4j.appender.archivoLDAPCarga.MaxFileSize','1000KB');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (66,'LOG','log4j.appender.archivoLDAPCarga.MaxBackupIndex','1');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (67,'LOG','log4j.appender.archivoLDAPCarga.layout','org.apache.log4j.PatternLayout');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (68,'LOG','log4j.appender.archivoLDAPCarga.layout.ConversionPattern','%d [%t] %-5p %c - %m%n');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (69,'LOG','log4j.category.LDAPCarga','DEBUG, consola, archivoLDAPCarga');
INSERT INTO "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) VALUES (70,'LOG','log4j.additivity.LDAPCarga','false');
COMMIT;

INSERT INTO "CONELE"."TBL_CE_IBM_TABLA" (ID, NOMBRE, NOMBRE_MOSTRAR, TIPO, BOTON_AGREGAR, BOTON_ACTUALIZAR, BOTON_ELIMINAR) VALUES ('129', 'TBL_CE_IBM_PARTICIPE_CC', 'Obtener Partícipes', '1', '0', '0', '0');
COMMIT;

INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('481', 'FLAG_MOSTRAR_INICIALES', '0', '103', '0', '1', 'Mostrar Iniciales', 'BOOLEAN', '0', '10', '0', '0');
COMMIT;

UPDATE "CONELE"."TBL_CE_IBM_PARAMETROS_CONF_CC" SET VALOR_VARIABLE = '2064.46addc9f-01d2-4afa-89d5-465d1ba89322' WHERE NOMBRE_VARIABLE = 'snapshotId';
COMMIT;

INSERT INTO "CONELE"."TBL_CE_IBM_MENSAJE_CC" (ID, DESCRIPCION) VALUES ('1', '¿Tiene Firmas?');
INSERT INTO "CONELE"."TBL_CE_IBM_TABLA" (ID, NOMBRE, NOMBRE_MOSTRAR, TIPO, BOTON_AGREGAR, BOTON_ACTUALIZAR, BOTON_ELIMINAR) VALUES ('130', 'TBL_CE_IBM_MENSAJE_CC', 'Mensajes', '1', '0', '1', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('495', 'ID', '1', '130', '1', '8', 'Id', 'INTEGER', '0', '1', '0', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('496', 'DESCRIPCION', '0', '130', '1', '150', 'Descripción', 'ALFANUMERICO', '0', '2', '0', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('497', 'CONTENIDO', '0', '130', '1', NULL, 'Contenido', 'BLOB', '0', '3', '0', '0');
COMMIT;
------------------------cambio en la tabla operacion ----------------------------------------
alter table  CONELE.Tbl_Ce_Ibm_Operacion_Cc add ESTADO number(1, 0) default 1;
update CONELE.Tbl_Ce_Ibm_Operacion_Cc set estado=0 where id=6;

commit;

spool off