spool 004_SCRIPT_r2.6.0_ejecutado.log

CREATE TABLE "CONELE"."TBL_CE_IBM_PERFIL_X_NIVEL_CC"  (
	"TIPO_NIVEL" NUMBER(10,0) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID_PERFIL_FK" NUMBER(5,0) NOT NULL ENABLE, 
	"FECHA_REGISTRO" TIMESTAMP (6), 
	"ID_EMPLEADO_FK" NUMBER(10,0), 
	"FLAG_ACTIVO" CHAR(1 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TBL_CE_IBM_PERFIL_X_NIVEL_PK" PRIMARY KEY ("TIPO_NIVEL", "VALOR") USING INDEX TABLESPACE "CONELE_IDX"  ENABLE, 
	 CONSTRAINT "PERFIL_X_NIVEL_PERFIL_FK" FOREIGN KEY ("ID_PERFIL_FK") REFERENCES "CONELE"."TBL_CE_IBM_PERFIL" ("ID") ENABLE, 
	 CONSTRAINT "PERFIL_X_NIVEL_EMP_FK" FOREIGN KEY ("ID_EMPLEADO_FK") REFERENCES "CONELE"."TBL_CE_IBM_EMPLEADO" ("ID") ENABLE
   )
  TABLESPACE "CONELE_DAT" ;

COMMENT ON COLUMN "CONELE"."TBL_CE_IBM_PERFIL_X_NIVEL_CC"."TIPO_NIVEL" IS '1=Usuario, 2=Puesto, 3=Oficina';
COMMENT ON COLUMN "CONELE"."TBL_CE_IBM_PERFIL_X_NIVEL_CC"."FLAG_ACTIVO" IS '1=Activo, 0=Inactivo';

GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_PERFIL_X_NIVEL_CC TO APP_CONELE;

INSERT INTO "CONELE"."TBL_CE_IBM_TABLA" (ID, NOMBRE, NOMBRE_MOSTRAR, TIPO, BOTON_AGREGAR, BOTON_ACTUALIZAR, BOTON_ELIMINAR) VALUES ('131', 'TBL_CE_IBM_PERFIL_X_NIVEL_CC', 'Asignación de Perfiles', '1', '1', '1', '1');
COMMIT;

--

CREATE TABLE "CONELE"."TBL_CE_IBM_CASO_NEGOCIO_CC" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"TEXTO_AYUDA" BLOB, 
	 CONSTRAINT "TBL_CE_IBM_CASO_NEGOCIO_C_PK" PRIMARY KEY ("ID") USING INDEX
  TABLESPACE "CONELE_IDX"  ENABLE
   ) 
  TABLESPACE "CONELE_DAT" ;

CREATE SEQUENCE  "CONELE"."SEQ_CE_IBM_CASO_NEGOCIO_CC"  MINVALUE 2 MAXVALUE 9999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;

GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_CASO_NEGOCIO_CC TO APP_CONELE;
GRANT SELECT ON CONELE.SEQ_CE_IBM_CASO_NEGOCIO_CC TO APP_CONELE;

INSERT INTO "CONELE"."TBL_CE_IBM_CASO_NEGOCIO_CC" (ID, DESCRIPCION) VALUES ('1', 'Ninguno');
INSERT INTO "CONELE"."TBL_CE_IBM_TABLA" (ID, NOMBRE, NOMBRE_MOSTRAR, TIPO, BOTON_AGREGAR, BOTON_ACTUALIZAR, BOTON_ELIMINAR) VALUES ('132', 'TBL_CE_IBM_CASO_NEGOCIO_CC', 'Casos de Negocio', '1', '1', '1', '1');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('505', 'ID', '1', '132', '1', '8', 'Id', 'INTEGER', '0', '1', '0', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('499', 'DESCRIPCION', '0', '132', '1', '200', 'Descripción', 'STRING', '0', '2', '1', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('500', 'TEXTO_AYUDA', '0', '132', '0', 'Ayuda', 'BLOB', '0', '3', '0', '0');

ALTER TABLE CONELE.TBL_CE_IBM_GUIA_DOCUMENT_CC ADD (
  ID_CASO_NEGOCIO_FK NUMBER(10,0) DEFAULT 1 NOT NULL ENABLE
);

ALTER TABLE CONELE.TBL_CE_IBM_GUIA_DOCUMENT_CC
ADD CONSTRAINT GUIA_DOCUMENT_CASONEGOCIO_FK
FOREIGN KEY (ID_CASO_NEGOCIO_FK)
REFERENCES CONELE.TBL_CE_IBM_CASO_NEGOCIO_CC(ID);

ALTER TABLE "CONELE"."TBL_CE_IBM_GUIA_DOCUMENT_CC" DROP PRIMARY KEY;

DROP INDEX "TBL_CE_IBM_GUIA_DOCUMENT__PK";

ALTER TABLE "CONELE"."TBL_CE_IBM_GUIA_DOCUMENT_CC" ADD CONSTRAINT GUIA_DOCUMENT_PK PRIMARY KEY ("ID_OPERACION_FK","ID_DOCUMENTO_FK","COD_TIPO_PJ","ID_CASO_NEGOCIO_FK");

ALTER TABLE CONELE.TBL_CE_IBM_EXPEDIENTE_CC ADD (
  ID_CASO_NEGOCIO_FK NUMBER(10,0)
);

ALTER TABLE CONELE.TBL_CE_IBM_EXPEDIENTE_CC
ADD CONSTRAINT EXPEDIENTE_CC_CASONEGOCIO_FK
FOREIGN KEY (ID_CASO_NEGOCIO_FK)
REFERENCES CONELE.TBL_CE_IBM_CASO_NEGOCIO_CC(ID);

UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '2' WHERE ID = 333;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '1' WHERE ID = 334;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '5' WHERE ID = 335;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '6', ES_REQUERIDO = '0' WHERE ID = 336;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '7', ES_REQUERIDO = '0' WHERE ID = 337;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '8', ES_REQUERIDO = '0' WHERE ID = 338;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '9', ES_REQUERIDO = '0' WHERE ID = 339;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '3' WHERE ID = 340;
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('501', 'ID_CASO_NEGOCIO_FK', '1', '114', '1', '5', 'Caso de Negocio', 'LISTA', '1', '4', '1', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_VALORES_FORANEOS" (ID, ID_COLUMNA, NOMBRE_TABLA, NOMBRE_COLUMNA, VALOR_COLUMNA) VALUES ('107', '501', 'TBL_CE_IBM_CASO_NEGOCIO_CC', 'DESCRIPCION', 'ID');
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET LONGITUD_MAXIMA = '200' WHERE ID = 322;

ALTER TABLE CONELE.TBL_CE_IBM_DOCUMENTO_CC ADD (
  FLAG_NRO_PAGINA VARCHAR2(1) DEFAULT 0 NOT NULL
);

INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('503', 'FLAG_NRO_PAGINA', '0', '111', '0', '1', 'Habilitar Nro Página', 'BOOLEAN', '0', '8', '0', '0');

ALTER TABLE CONELE.TBL_CE_IBM_DOCUMENTO_EXP_CC ADD (
  NRO_PAGINA NUMBER(5,0)
);

INSERT INTO "CONELE"."TBL_CE_IBM_MENSAJE_CC" (ID, DESCRIPCION, CONTENIDO) VALUES ('2', 'Advertencia Documento Combinado', UTL_RAW.CAST_TO_RAW('Documento combinado. Revisar'));
COMMIT;


--=========================================== Cuenta Proveedora y Rol Migrador ===========================================--
INSERT INTO CONELE.TBL_CE_IBM_MULTITABLA (ID, TIPO, NOMBRE, DESCRIPCION, ESTADO, CODIGO_ETI, CODIGO_HABIL, TEXTO_ETI, TEXTO_HABIL, FECHA_CREA, USU_CREA)
VALUES (101, '1', 'Productos exonerados comisión', 'Productos exonerados comisión', 'A', 'Código de Producto', 'S', 'Código de Sub Producto', 'S', sysdate, 'ADMIN');

INSERT INTO CONELE.TBL_CE_IBM_MULTITABLA (ID, ID_PARAMETRIA, TIPO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, CODIGO_ETI, CODIGO_HABIL, TEXTO, TEXTO_ETI, TEXTO_HABIL, FECHA_CREA, USU_CREA)
VALUES (102, 101, '2', 'CTA.CTE.PROVEEDOR PJ PEN', 'Productos exonerados comisión', 'A', '01', 'Código de Producto', 'S', '0061', 'Código de Sub Producto', 'S', sysdate, 'ADMIN');

INSERT INTO CONELE.TBL_CE_IBM_MULTITABLA (ID, ID_PARAMETRIA, TIPO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, CODIGO_ETI, CODIGO_HABIL, TEXTO, TEXTO_ETI, TEXTO_HABIL, FECHA_CREA, USU_CREA)
VALUES (103, 101, '2', 'CTA.CTE.PROVEEDOR PJ USD', 'Productos exonerados comisión', 'A', '01', 'Código de Producto', 'S', '0062', 'Código de Sub Producto', 'S', sysdate, 'ADMIN');

INSERT INTO CONELE.TBL_CE_IBM_MULTITABLA (ID, ID_PARAMETRIA, TIPO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, CODIGO_ETI, CODIGO_HABIL, TEXTO, TEXTO_ETI, TEXTO_HABIL, FECHA_CREA, USU_CREA)
VALUES (104, 101, '2', 'CTA.CTE.PROVEEDOR PNN PEN', 'Productos exonerados comisión', 'A', '01', 'Código de Producto', 'S', '0067', 'Código de Sub Producto', 'S', sysdate, 'ADMIN');

INSERT INTO CONELE.TBL_CE_IBM_MULTITABLA (ID, ID_PARAMETRIA, TIPO, NOMBRE, DESCRIPCION, ESTADO, CODIGO, CODIGO_ETI, CODIGO_HABIL, TEXTO, TEXTO_ETI, TEXTO_HABIL, FECHA_CREA, USU_CREA)
VALUES (105, 101, '2', 'CTA.CTE.PROVEEDOR PNN USD', 'Productos exonerados comisión', 'A', '01', 'Código de Producto', 'S', '0068', 'Código de Sub Producto', 'S', sysdate, 'ADMIN');
COMMIT;

INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC (ID, CODIGO_MODULO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES (71, 'CONF', 'flagFinalizarBastanteo', '1');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC (ID, CODIGO_MODULO, NOMBRE_VARIABLE, VALOR_VARIABLE) VALUES (72, 'CONF', 'flagTerminarVinculacion', '1');
COMMIT;

spool off