//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.ctacte.servicio.cm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actualizarEstadoDocumento_CC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actualizarEstadoDocumento_CC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idExpediente" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="idDocumento" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="flagCM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idCM" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="pidCM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actualizarEstadoDocumento_CC", propOrder = {
    "idExpediente",
    "idDocumento",
    "flagCM",
    "idCM",
    "pidCM"
})
public class ActualizarEstadoDocumentoCC {

    protected int idExpediente;
    protected int idDocumento;
    protected String flagCM;
    protected int idCM;
    protected String pidCM;

    /**
     * Gets the value of the idExpediente property.
     * 
     */
    public int getIdExpediente() {
        return idExpediente;
    }

    /**
     * Sets the value of the idExpediente property.
     * 
     */
    public void setIdExpediente(int value) {
        this.idExpediente = value;
    }

    /**
     * Gets the value of the idDocumento property.
     * 
     */
    public int getIdDocumento() {
        return idDocumento;
    }

    /**
     * Sets the value of the idDocumento property.
     * 
     */
    public void setIdDocumento(int value) {
        this.idDocumento = value;
    }

    /**
     * Gets the value of the flagCM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagCM() {
        return flagCM;
    }

    /**
     * Sets the value of the flagCM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagCM(String value) {
        this.flagCM = value;
    }

    /**
     * Gets the value of the idCM property.
     * 
     */
    public int getIdCM() {
        return idCM;
    }

    /**
     * Sets the value of the idCM property.
     * 
     */
    public void setIdCM(int value) {
        this.idCM = value;
    }

    /**
     * Gets the value of the pidCM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPidCM() {
        return pidCM;
    }

    /**
     * Sets the value of the pidCM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPidCM(String value) {
        this.pidCM = value;
    }

}
