//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.ctacte.servicio.cm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for documentoExpediente complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentoExpediente">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="docPesoPromKB" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="fechaEscaneo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="fechaVigencia" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="flagAlterno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagCm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagEscaneado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagObligatorio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagRechazado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flagReqEscaneo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idCm" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idCmCopia" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idDocumento" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idExpediente" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idMotivo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="nombreArchivo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pidCM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentoExpediente", propOrder = {
    "docPesoPromKB",
    "fechaEscaneo",
    "fechaVigencia",
    "flagAlterno",
    "flagCm",
    "flagEscaneado",
    "flagObligatorio",
    "flagRechazado",
    "flagReqEscaneo",
    "id",
    "idCm",
    "idCmCopia",
    "idDocumento",
    "idExpediente",
    "idMotivo",
    "nombreArchivo",
    "pidCM"
})
public class DocumentoExpediente {

    protected Integer docPesoPromKB;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEscaneo;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaVigencia;
    protected String flagAlterno;
    protected String flagCm;
    protected String flagEscaneado;
    protected String flagObligatorio;
    protected String flagRechazado;
    protected String flagReqEscaneo;
    protected Integer id;
    protected Integer idCm;
    protected Integer idCmCopia;
    protected Integer idDocumento;
    protected Integer idExpediente;
    protected Integer idMotivo;
    protected String nombreArchivo;
    protected String pidCM;

    /**
     * Gets the value of the docPesoPromKB property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDocPesoPromKB() {
        return docPesoPromKB;
    }

    /**
     * Sets the value of the docPesoPromKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDocPesoPromKB(Integer value) {
        this.docPesoPromKB = value;
    }

    /**
     * Gets the value of the fechaEscaneo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEscaneo() {
        return fechaEscaneo;
    }

    /**
     * Sets the value of the fechaEscaneo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEscaneo(XMLGregorianCalendar value) {
        this.fechaEscaneo = value;
    }

    /**
     * Gets the value of the fechaVigencia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaVigencia() {
        return fechaVigencia;
    }

    /**
     * Sets the value of the fechaVigencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaVigencia(XMLGregorianCalendar value) {
        this.fechaVigencia = value;
    }

    /**
     * Gets the value of the flagAlterno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagAlterno() {
        return flagAlterno;
    }

    /**
     * Sets the value of the flagAlterno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagAlterno(String value) {
        this.flagAlterno = value;
    }

    /**
     * Gets the value of the flagCm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagCm() {
        return flagCm;
    }

    /**
     * Sets the value of the flagCm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagCm(String value) {
        this.flagCm = value;
    }

    /**
     * Gets the value of the flagEscaneado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagEscaneado() {
        return flagEscaneado;
    }

    /**
     * Sets the value of the flagEscaneado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagEscaneado(String value) {
        this.flagEscaneado = value;
    }

    /**
     * Gets the value of the flagObligatorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagObligatorio() {
        return flagObligatorio;
    }

    /**
     * Sets the value of the flagObligatorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagObligatorio(String value) {
        this.flagObligatorio = value;
    }

    /**
     * Gets the value of the flagRechazado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagRechazado() {
        return flagRechazado;
    }

    /**
     * Sets the value of the flagRechazado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagRechazado(String value) {
        this.flagRechazado = value;
    }

    /**
     * Gets the value of the flagReqEscaneo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagReqEscaneo() {
        return flagReqEscaneo;
    }

    /**
     * Sets the value of the flagReqEscaneo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagReqEscaneo(String value) {
        this.flagReqEscaneo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the idCm property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdCm() {
        return idCm;
    }

    /**
     * Sets the value of the idCm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdCm(Integer value) {
        this.idCm = value;
    }

    /**
     * Gets the value of the idCmCopia property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdCmCopia() {
        return idCmCopia;
    }

    /**
     * Sets the value of the idCmCopia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdCmCopia(Integer value) {
        this.idCmCopia = value;
    }

    /**
     * Gets the value of the idDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdDocumento() {
        return idDocumento;
    }

    /**
     * Sets the value of the idDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdDocumento(Integer value) {
        this.idDocumento = value;
    }

    /**
     * Gets the value of the idExpediente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdExpediente() {
        return idExpediente;
    }

    /**
     * Sets the value of the idExpediente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdExpediente(Integer value) {
        this.idExpediente = value;
    }

    /**
     * Gets the value of the idMotivo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdMotivo() {
        return idMotivo;
    }

    /**
     * Sets the value of the idMotivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdMotivo(Integer value) {
        this.idMotivo = value;
    }

    /**
     * Gets the value of the nombreArchivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreArchivo() {
        return nombreArchivo;
    }

    /**
     * Sets the value of the nombreArchivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreArchivo(String value) {
        this.nombreArchivo = value;
    }

    /**
     * Gets the value of the pidCM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPidCM() {
        return pidCM;
    }

    /**
     * Sets the value of the pidCM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPidCM(String value) {
        this.pidCM = value;
    }

}
