--------------------------------------------------------
--  DDL for Trigger TRG_CE_IBM_EXPEDIENTE_CC
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONELE"."TRG_CE_IBM_EXPEDIENTE_CC" 
BEFORE UPDATE ON CONELE.TBL_CE_IBM_EXPEDIENTE_CC
REFERENCING OLD AS O NEW AS N
FOR EACH ROW
DECLARE
  N_IDLOG NUMBER(10,0);
  V_DESC VARCHAR2(400) :=' ';
BEGIN
  IF NVL(:N.ID_CAMPANIA_FK,0) <> NVL(:O.ID_CAMPANIA_FK,0) THEN     
     SELECT CONCAT('Se ha modificado el campo CAMPAÑA al valor ',UPPER(DESCRIPCION)) INTO V_DESC FROM CONELE.TBL_CE_IBM_CAMPANIA_CC WHERE ID = :N.ID_CAMPANIA_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);
  END IF;
  IF NVL(:N.ID_CLIENTE_FK,0) <> NVL(:O.ID_CLIENTE_FK,0) THEN    
     SELECT CONCAT('Se ha modificado el campo CLIENTE al valor ',UPPER(NUMERO_DOI)) INTO V_DESC FROM CONELE.TBL_CE_IBM_CLIENTE_CC WHERE ID = :N.ID_CLIENTE_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);
  END IF;   
  IF NVL(:N.ID_EMPLEADO_FK,0) <> NVL(:O.ID_EMPLEADO_FK,0) THEN    
     SELECT CONCAT('Se ha modificado el campo EMPLEADO al valor ',UPPER(CODIGO)) INTO V_DESC FROM CONELE.TBL_CE_IBM_EMPLEADO WHERE ID = :N.ID_EMPLEADO_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.ID_ESTADO_FK,0) <> NVL(:O.ID_ESTADO_FK,0) THEN    
     SELECT CONCAT('Se ha modificado el campo ESTADO al valor ',UPPER(DESCRIPCION)) INTO V_DESC FROM CONELE.TBL_CE_IBM_ESTADO_EXP_CC WHERE ID = :N.ID_ESTADO_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.ID_MOTIVO_FK,0) <> NVL(:O.ID_MOTIVO_FK,0) THEN   
     IF (:N.ID_MOTIVO_FK <> 0) THEN
         SELECT CONCAT('Se ha modificado el campo MOTIVO al valor ',UPPER(DESCRIPCION)) INTO V_DESC FROM CONELE.TBL_CE_IBM_MOTIVO_CC WHERE ID = :N.ID_MOTIVO_FK;
         INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
         VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
     END IF;
  END IF;  
  IF NVL(:N.ID_OFICINA_FK,0) <> NVL(:O.ID_OFICINA_FK,0) THEN     
     SELECT CONCAT('Se ha modificado el campo OFICINA al valor ',UPPER(DESCRIPCION)) INTO V_DESC FROM CONELE.TBL_CE_IBM_OFICINA WHERE ID = :N.ID_OFICINA_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);
  END IF;
  IF NVL(:N.ID_OPERACION_FK,0) <> NVL(:O.ID_OPERACION_FK,0) THEN     
     SELECT CONCAT('Se ha modificado el campo OPERACION al valor ',UPPER(DESCRIPCION)) INTO V_DESC FROM CONELE.TBL_CE_IBM_OPERACION_CC WHERE ID = :N.ID_OPERACION_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);
  END IF;
  IF NVL(:N.ID_PRODUCTO_FK,0) <> NVL(:O.ID_PRODUCTO_FK,0) THEN     
     SELECT CONCAT('Se ha modificado el campo PRODUCTO al valor ',UPPER(DESCRIPCION)) INTO V_DESC FROM CONELE.TBL_CE_IBM_PRODUCTO_CC WHERE ID = :N.ID_PRODUCTO_FK;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);
  END IF;

  IF NVL(:N.ACCION,' ') <> NVL(:O.ACCION,' ') THEN    
     V_DESC := 'Se ha modificado el campo ACCION al valor '||:N.ACCION;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF; 
  IF NVL(:N.COD_TIPO_PJ,' ') <> NVL(:O.COD_TIPO_PJ,' ') THEN    
     V_DESC := 'Se ha modificado el campo COD TIPO PERSONA JURIDICA al valor '||:N.COD_TIPO_PJ;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF; 
  IF NVL(:N.CUENTA_COBRO_COMISION,' ') <> NVL(:O.CUENTA_COBRO_COMISION,' ') THEN    
     V_DESC := 'Se ha modificado el campo CUENTA COBRO COMISION al valor '||:N.CUENTA_COBRO_COMISION;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF; 
  IF NVL(:N.DES_TIPO_PJ,' ') <> NVL(:O.DES_TIPO_PJ,' ') THEN    
     V_DESC := 'Se ha modificado el campo DES TIPO PERSONA JURIDICA al valor '||:N.DES_TIPO_PJ;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.ESTADO_CUENTA,' ') <> NVL(:O.ESTADO_CUENTA,' ') THEN    
     V_DESC := 'Se ha modificado el campo ESTADO_CUENTA al valor '||:N.ESTADO_CUENTA;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  
  IF NVL(TO_CHAR(:N.FECHA_ENVIO,'YYYYMMDD'),'        ') <> NVL(TO_CHAR(:O.FECHA_ENVIO,'YYYYMMDD'),'        ') THEN    
     V_DESC := 'Se ha modificado el campo FECHA ENVIO al valor '||:N.FECHA_ENVIO;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;  
  IF NVL(TO_CHAR(:N.FECHA_FIN,'YYYYMMDD'),'        ') <> NVL(TO_CHAR(:O.FECHA_FIN,'YYYYMMDD'),'        ') THEN    
     V_DESC := 'Se ha modificado el campo FECHA FIN al valor '||:N.FECHA_FIN;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(TO_CHAR(:N.FECHA_PROGRAMADA,'YYYYMMDD'),'        ') <> NVL(TO_CHAR(:O.FECHA_PROGRAMADA,'YYYYMMDD'),'        ') THEN    
     V_DESC := 'Se ha modificado el campo FECHA PROGRAMADA al valor '||:N.FECHA_PROGRAMADA;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(TO_CHAR(:N.FECHA_REGISTRO,'YYYYMMDD'),'        ') <> NVL(TO_CHAR(:O.FECHA_REGISTRO,'YYYYMMDD'),'        ') THEN    
     V_DESC := 'Se ha modificado el campo FECHA REGISTRO al valor '||:N.FECHA_REGISTRO;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  
  IF NVL(:N.FLAG_CONFORMIDAD_BASTANTEO,' ') <> NVL(:O.FLAG_CONFORMIDAD_BASTANTEO,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG CONFORMIDAD BASTANTEO al valor '||:N.FLAG_CONFORMIDAD_BASTANTEO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.FLAG_CORREO,' ') <> NVL(:O.FLAG_CORREO,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG CORREO al valor '||:N.FLAG_CORREO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;  
  IF NVL(:N.FLAG_EJECUTO_COBRO_COMISION,' ') <> NVL(:O.FLAG_EJECUTO_COBRO_COMISION,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG EJECUTO COBRO COMISION al valor '||:N.FLAG_EJECUTO_COBRO_COMISION;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;   
  IF NVL(:N.FLAG_EXONERACION_COMISION,' ') <> NVL(:O.FLAG_EXONERACION_COMISION,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG EXONERACION COMISION al valor '||:N.FLAG_EXONERACION_COMISION;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;   
  IF NVL(:N.FLAG_FACULTADES_ESPECIALES,' ') <> NVL(:O.FLAG_FACULTADES_ESPECIALES,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG FACULTADES ESPECIALES al valor '||:N.FLAG_FACULTADES_ESPECIALES;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;   
  IF NVL(:N.FLAG_MODIFICATORIA,' ') <> NVL(:O.FLAG_MODIFICATORIA,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG MODIFICATORIA al valor '||:N.FLAG_MODIFICATORIA;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;   
  IF NVL(:N.FLAG_SMSTEXTO,' ') <> NVL(:O.FLAG_SMSTEXTO,' ') THEN    
     V_DESC := 'Se ha modificado el campo FLAG SMSTEXTO al valor '||:N.FLAG_SMSTEXTO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;  
  
  IF NVL(:N.NUMERO_CUENTA_COBRO,' ') <> NVL(:O.NUMERO_CUENTA_COBRO,' ') THEN    
     V_DESC := 'Se ha modificado el campo NUMERO CUENTA COBRO al valor '||:N.NUMERO_CUENTA_COBRO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;  
  IF NVL(:N.NUM_TERMINAL,' ') <> NVL(:O.NUM_TERMINAL,' ') THEN    
     V_DESC := 'Se ha modificado el campo NUM. TERMINAL al valor '||:N.NUM_TERMINAL;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;  
  IF NVL(:N.OBSERVACIONES,' ') <> NVL(:O.OBSERVACIONES,' ') THEN    
     V_DESC := 'Se ha modificado el campo OBSERVACIONES al valor '||:N.OBSERVACIONES;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.OBSERVACIONES_BASTANTEO,' ') <> NVL(:O.OBSERVACIONES_BASTANTEO,' ') THEN    
     V_DESC := 'Se ha modificado el campo OBSERVACIONES BASTANTEO al valor '||:N.OBSERVACIONES_BASTANTEO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.RESULTADO,' ') <> NVL(:O.RESULTADO,' ') THEN    
     V_DESC := 'Se ha modificado el campo RESULTADO al valor '||:N.RESULTADO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.RESULTADO_BASTANTEO,0) <> NVL(:O.RESULTADO_BASTANTEO,0) THEN    
     V_DESC := 'Se ha modificado el campo RESULTADO BASTANTEO al valor '||:N.RESULTADO_BASTANTEO;
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);	 
  END IF;
  IF NVL(:N.SUBPRODUCTO,' ') <> NVL(:O.SUBPRODUCTO,' ') THEN         
	 V_DESC := 'Se ha modificado el campo SUBPRODUCTO al valor '||:N.SUBPRODUCTO;	 
     INSERT INTO CONELE.TBL_CE_IBM_LOG_CC(ID, EXPEDIENTE_FK, DESCRIPCION, NUM_TERMINAL, ID_EMPLEADO_FK, ID_ESTADO_FK) 
     VALUES(CONELE.SEQ_CE_IBM_LOG_CC.NEXTVAL, :N.ID, V_DESC, :N.NUM_TERMINAL, :N.ID_EMPLEADO_FK, :N.ID_ESTADO_FK);     	 
  END IF; 
END;
/
ALTER TRIGGER "CONELE"."TRG_CE_IBM_EXPEDIENTE_CC" ENABLE;
