
--registra usuario y passwor del servidor ftp	
Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('31','5','ftp.user','XXXXXXXXXXXXXXX');

Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('32','5','ftp.pass','XXXXXXXXXXXXXXX');
-- registrar usuario y password del Content Manager
Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('35','5','cmuserid','XXXXXXXXXXXXXXX');

Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('36','5','cmpassword','XXXXXXXXXXXXXXX');
--registra usuario y passwor del servidor ftp	
Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('61','1','CONSTANTE_FTP_USER','XXXXXXXXXXXXXXX');

Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('62','1','CONSTANTE_FTP_PASSWORD','XXXXXXXXXXXXXXX');
--registrar password del usuario userAD
Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF (ID,CODIGO_APLICATIVO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('44','1','REST_PASSWORD_ADMIN','XXXXXXXXXXXXXXX');

--registra usuario y passwor del servidor ftp	
Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('22','CONF','usuarioFTP','XXXXXXXXXXXXXXX');

Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('23','CONF','passwordFTP','XXXXXXXXXXXXXXX');
--registrar password del usuario userAD
Insert into CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC (ID,CODIGO_MODULO,NOMBRE_VARIABLE,VALOR_VARIABLE) values ('31','CONF','passwordAdminProcess','XXXXXXXXXXXXXXX');

commit;