UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET BUSQUEDA = '1' WHERE ID = 297;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET BUSQUEDA = '1' WHERE ID = 298;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET BUSQUEDA = '1' WHERE ID = 305;

UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '6' WHERE ID = 297;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '7' WHERE ID = 298;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '8' WHERE ID = 299;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '11' WHERE ID = 302;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '13' WHERE ID = 304;
UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ORDEN_COLUMNA = '14' WHERE ID = 305;

INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('387', 'ID_NIVEL_FK', '0', '105', '0', '5', 'Nivel para Delegación de Oficina', 'LISTA', '1', '9', '1', '0');
INSERT INTO "CONELE"."TBL_CE_IBM_COLUMNA" (ID, NOMBRE, ES_LLAVE_PRIMARIA, ID_TABLA, ES_REQUERIDO, LONGITUD_MAXIMA, NOMBRE_MOSTRAR, TIPO_DATO, ES_LLAVE_FORANEA, ORDEN_COLUMNA, BUSQUEDA, FLAG_DEPENDENCIA) VALUES ('388', 'ID_TIPO_CATEGORIA_FK', '0', '105', '0', '5', 'Categoría para Riesgos', 'LISTA', '1', '10', '1', '0');

INSERT INTO "CONELE"."TBL_CE_IBM_VALORES_FORANEOS" (ID, ID_COLUMNA, NOMBRE_TABLA, NOMBRE_COLUMNA, VALOR_COLUMNA) VALUES ('60', '387', 'TBL_CE_IBM_NIVEL', 'DESCRIPCION', 'ID');
INSERT INTO "CONELE"."TBL_CE_IBM_VALORES_FORANEOS" (ID, ID_COLUMNA, NOMBRE_TABLA, NOMBRE_COLUMNA, VALOR_COLUMNA) VALUES ('61', '388', 'TBL_CE_IBM_TIPO_CATEGORIA', 'DESCRIPCION', 'ID');

UPDATE "CONELE"."TBL_CE_IBM_COLUMNA" SET ES_LLAVE_PRIMARIA = '1' WHERE ID=340; 

COMMIT; 