//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.com.grupobbva.accpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import pe.com.grupobbva.accpj.pj.CtBuscarPersonaJuridicaRq;
import pe.com.grupobbva.accpj.pj.CtBuscarPersonaJuridicaRs;

@WebService(name = "ACCPJ_ServiciosWeb_PortType", targetNamespace = "http://grupobbva.com.pe/accpj/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    pe.com.grupobbva.accpj.pey4.ObjectFactory.class,
    pe.com.grupobbva.accpj.pj.ObjectFactory.class,
    pe.com.grupobbva.accpj.rela.ObjectFactory.class
})
public interface ACCPJServiciosWebPortType {


    /**
     * 
     * @param consultarRelacionesRq
     * @return
     *     returns pe.com.grupobbva.accpj.rela.CtConsultarRelacionesRs
     */
    @WebMethod(action = "http://grupobbva.com.pe/accpj/consultarRelaciones")
    @WebResult(name = "ConsultarRelacionesRs", targetNamespace = "http://grupobbva.com.pe/accpj/rela/", partName = "ConsultarRelacionesRs")
    public pe.com.grupobbva.accpj.rela.CtConsultarRelacionesRs consultarRelaciones(
        @WebParam(name = "ConsultarRelacionesRq", targetNamespace = "http://grupobbva.com.pe/accpj/rela/", partName = "ConsultarRelacionesRq")
        pe.com.grupobbva.accpj.rela.CtConsultarRelacionesRq consultarRelacionesRq);

    /**
     * 
     * @param buscarPersonaJuridicaRq
     * @return
     *     returns pe.com.grupobbva.accpj.pj.CtBuscarPersonaJuridicaRs
     */
    @WebMethod(action = "http://grupobbva.com.pe/accpj/buscarPersonaJuridica")
    @WebResult(name = "BuscarPersonaJuridicaRs", targetNamespace = "http://grupobbva.com.pe/accpj/pj/", partName = "BuscarPersonaJuridicaRs")
    public CtBuscarPersonaJuridicaRs buscarPersonaJuridica(
        @WebParam(name = "BuscarPersonaJuridicaRq", targetNamespace = "http://grupobbva.com.pe/accpj/pj/", partName = "BuscarPersonaJuridicaRq")
        CtBuscarPersonaJuridicaRq buscarPersonaJuridicaRq);

    /**
     * 
     * @param consultarRelacionesPaginadoRq
     * @return
     *     returns pe.com.grupobbva.accpj.pey4.CtConsultarRelacionesRs
     */
    @WebMethod(operationName = "ConsultarRelacionesPaginado", action = "http://grupobbva.com.pe/accpj/ConsultarRelacionesPaginado")
    @WebResult(name = "ConsultarRelacionesPaginadoRs", targetNamespace = "http://grupobbva.com.pe/accpj/pey4/", partName = "ConsultarRelacionesPaginadoRs")
    public pe.com.grupobbva.accpj.pey4.CtConsultarRelacionesRs consultarRelacionesPaginado(
        @WebParam(name = "ConsultarRelacionesPaginadoRq", targetNamespace = "http://grupobbva.com.pe/accpj/pey4/", partName = "ConsultarRelacionesPaginadoRq")
        pe.com.grupobbva.accpj.pey4.CtConsultarRelacionesRq consultarRelacionesPaginadoRq);

}
