spool 006_loadinitdata.log replace;
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 14, 'TABLAGENERAL_SERVICE_URL', 'http://118.180.60.133/general/services/TablaGeneral');
-------------------------------------------------------------08012015------------------------
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'PACKPYME_SERVICE_URL', 'http://118.180.36.26:7830/cttactpass/cvalnrocttcli');

UPDATE CONELE.TBL_CE_IBM_PRODUCTO_TAREA FLAG_VALIDACION SET FLAG_VALIDACION = 0;
UPDATE CONELE.TBL_CE_IBM_PRODUCTO_TAREA FLAG_VALIDACION SET FLAG_VALIDACION = 1 WHERE ID_TAREA_FK IN (3,7,14,18);

-------------------------------------------------------------------14012015------------------------
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_CODEMPRESA', ' ');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_CODTERMINALEMPRESA', ' ');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_CANAL', ' ');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_CODAPLICACION', ' ');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_IDPETICIONEMPRESA', ' ');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_IDPETICIONBANCO', ' ');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_IDOPERACION', 'CVALNROCTTCLI');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_IDSERVICIO', 'SCTTACTPASS');
INSERT INTO CONELE.TBL_CE_IBM_PARAMETROS_CONF VALUES(SEQ_CE_IBM_PARAMETROS_CONF.nextval, 15, 'CABECERA_IDINTERCONEXION', 'CTTACTPASS');
INSERT INTO CONELE.TBL_CE_IBM_TABLA(ID, NOMBRE,NOMBRE_MOSTRAR,TIPO,BOTON_AGREGAR,BOTON_ACTUALIZAR,BOTON_ELIMINAR,ORDEN) VALUES(67,'TBL_CE_IBM_MENSAJE_CE','Mensajes Unificado',1,0,1,0,null);
INSERT INTO CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values ('1','Busqueda Expediente Bandeja Busqueda : Busqueda Sin filtro');
INSERT INTO CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values ('2','Busqueda Expediente Bandeja Busqueda : Busqueda por Expediente');
INSERT INTO CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values ('3','Busqueda otros Criterios');
INSERT INTO CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values ('7','WSPackPyme Respuesta: Contrato no corresponde al cliente (COD 10).');
INSERT INTO CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values ('8','WSPackPyme Respuesta: Contrato no encontrado (COD 20).');
INSERT INTO CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values ('9','WSPackPyme Respuesta: Error en acceso (COD 99).');
Insert into CONELE.TBL_CE_IBM_COLUMNA (ID,NOMBRE,ES_LLAVE_PRIMARIA,ID_TABLA,ES_REQUERIDO,LONGITUD_MAXIMA,NOMBRE_MOSTRAR,TIPO_DATO,ES_LLAVE_FORANEA,ORDEN_COLUMNA,BUSQUEDA,PLANTILLA,FLAG_DEPENDENCIA) values ('498','FLAG_VALIDACION','0','63','1','1','Flag Validar Contrato','BOOLEAN','0','3','0',null,'0');

---------------------------------------------------22012015--------------------------------

INSERT INTO CONELE.tbl_ce_ibm_estado_ce VALUES (22, 'Error');

INSERT INTO CONELE.tbl_ce_ibm_tarea_ad VALUES (50, '50', 'Gestionar documentos CM', null);
INSERT INTO CONELE.tbl_ce_ibm_tarea_ad VALUES (51, '51', 'Gestionar servicios Web', null);

-----------------------------------------------------------------28/01/2015-----------------------------------
ALTER TABLE CONELE.TBL_CE_IBM_PERFIL_CE  ADD FLAG_MENU_BAND_MONITOREO varchar2(1) default '0';

UPDATE CONELE.TBL_CE_IBM_PERFIL_CE SET FLAG_ADMINISTRACION = 1, FLAG_MENU_BAND_MONITOREO = 1 WHERE CODIGO = 14;

INSERT INTO CONELE.TBL_CE_IBM_COLUMNA (ID,NOMBRE,ES_LLAVE_PRIMARIA,ID_TABLA,ES_REQUERIDO,LONGITUD_MAXIMA,NOMBRE_MOSTRAR,TIPO_DATO,ES_LLAVE_FORANEA,ORDEN_COLUMNA,BUSQUEDA,PLANTILLA,FLAG_DEPENDENCIA) VALUES (504,'FLAG_MENU_BAND_MONITOREO','0',16,'0',1,'Flag Menu Bandeja Monitoreo','BOOLEAN','0',21,'0',null,'0');

-------------------------------------------------23/02/2015----------------------------------------
delete from conele.tbl_ce_ibm_valores_foraneos where id_columna in (select id from conele.tbl_ce_ibm_columna where id_tabla=5);

delete from conele.tbl_ce_ibm_columna where id_tabla=5;

Insert into CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values (10,'Mensaje Empleado no se puede cambiar perfil');
Insert into CONELE.TBL_CE_IBM_MENSAJE_CE (ID,DESCRIPCION) values (11,'Mensaje  Empleado no se puede inactivar');
-------------------------------------------------------------------03/02/2015---------------------------------------------
UPDATE "CONELE"."TBL_CE_IBM_PARAMETROS_CONF" SET VALOR_VARIABLE = '2064.ff8b9562-968c-4507-9753-8f0e98b14419' WHERE NOMBRE_VARIABLE = 'REST_SNAPSHOP_ID';
UPDATE "CONELE"."TBL_CE_IBM_PARAMETROS_CONF" SET VALOR_VARIABLE = '0' WHERE NOMBRE_VARIABLE = 'feriados.cargaActivo';

COMMIT;
spool off;