spool 007_grant.log replace ;
grant execute on CONELE.PG_CE_REPORTE to app_conele;
grant execute on CONELE.PG_CE_REPORTE_TC to app_conele;
---------------------------------22012015-------------------------
GRANT SELECT ON CONELE.SEQ_CE_IBM_MENSAJE_CE TO APP_CONELE; 
GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_MENSAJE_CE TO APP_CONELE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_LOG_ERRORES TO CONELE;
GRANT SELECT ON CONELE.SEQ_CE_IBM_LOG_ERRORES TO CONELE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_EMPLEADO_AD_CE TO CONELE;
GRANT SELECT ON CONELE.SEQ_CE_IBM_EMPLEADO_AD_CE TO CONELE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_HISTORIAL_LOG TO CONELE;
GRANT SELECT ON CONELE.SEQ_CE_IBM_HISTORIAL_LOG TO CONELE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONELE.TBL_CE_IBM_TAREA_AD TO CONELE;
grant execute on CONELE.PG_CE_REPORTE_TC to app_conele;    

spool off;