//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.service.business;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.bbva.service.business package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DelegacionRiesgos_QNAME = new QName("http://business.service.bbva.ibm.com/", "delegacionRiesgos");
    private final static QName _RetraerTareasResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "retraerTareasResponse");
    private final static QName _DelegacionOficinaMemoria_QNAME = new QName("http://business.service.bbva.ibm.com/", "delegacionOficinaMemoria");
    private final static QName _PautasClasificacionMemoriaResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "pautasClasificacionMemoriaResponse");
    private final static QName _PautasClasificacionBD_QNAME = new QName("http://business.service.bbva.ibm.com/", "pautasClasificacionBD");
    private final static QName _LineaMaximaMemoria_QNAME = new QName("http://business.service.bbva.ibm.com/", "lineaMaximaMemoria");
    private final static QName _LineaMaximaMemoriaResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "lineaMaximaMemoriaResponse");
    private final static QName _ActualizaEmpleadoExpediente_QNAME = new QName("http://business.service.bbva.ibm.com/", "actualizaEmpleadoExpediente");
    private final static QName _LineaMaximaBDResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "lineaMaximaBDResponse");
    private final static QName _ObtenerUsuarioResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "obtenerUsuarioResponse");
    private final static QName _PautasClasificacionMemoria_QNAME = new QName("http://business.service.bbva.ibm.com/", "pautasClasificacionMemoria");
    private final static QName _ActualizarDocumentoExpTC_QNAME = new QName("http://business.service.bbva.ibm.com/", "actualizarDocumentoExpTC");
    private final static QName _ObtenerParametroProcesoResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "obtenerParametroProcesoResponse");
    private final static QName _LineaMaximaBD_QNAME = new QName("http://business.service.bbva.ibm.com/", "lineaMaximaBD");
    private final static QName _DelegacionOficinaMemoriaResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "delegacionOficinaMemoriaResponse");
    private final static QName _DelegacionOficinaBDResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "delegacionOficinaBDResponse");
    private final static QName _RetraerTareas_QNAME = new QName("http://business.service.bbva.ibm.com/", "retraerTareas");
    private final static QName _DistribucionCargaResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "distribucionCargaResponse");
    private final static QName _ActualizaEmpleadoExpedienteResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "actualizaEmpleadoExpedienteResponse");
    private final static QName _ConsultarDocumentoExpediente_QNAME = new QName("http://business.service.bbva.ibm.com/", "consultarDocumentoExpediente");
    private final static QName _ObtenerUsuario_QNAME = new QName("http://business.service.bbva.ibm.com/", "obtenerUsuario");
    private final static QName _DistribucionCarga_QNAME = new QName("http://business.service.bbva.ibm.com/", "distribucionCarga");
    private final static QName _ConsultarDocumentoExpedienteResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "consultarDocumentoExpedienteResponse");
    private final static QName _DelegacionOficinaBD_QNAME = new QName("http://business.service.bbva.ibm.com/", "delegacionOficinaBD");
    private final static QName _ActualizarDocumentoExpTCResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "actualizarDocumentoExpTCResponse");
    private final static QName _PautasClasificacionBDResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "pautasClasificacionBDResponse");
    private final static QName _ObtenerParametroProceso_QNAME = new QName("http://business.service.bbva.ibm.com/", "obtenerParametroProceso");
    private final static QName _DelegacionRiesgosResponse_QNAME = new QName("http://business.service.bbva.ibm.com/", "delegacionRiesgosResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.bbva.service.business
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActualizaEmpleadoExpedienteResponse }
     * 
     */
    public ActualizaEmpleadoExpedienteResponse createActualizaEmpleadoExpedienteResponse() {
        return new ActualizaEmpleadoExpedienteResponse();
    }

    /**
     * Create an instance of {@link ObtenerUsuarioResponse }
     * 
     */
    public ObtenerUsuarioResponse createObtenerUsuarioResponse() {
        return new ObtenerUsuarioResponse();
    }

    /**
     * Create an instance of {@link LineaMaximaMemoriaResponse }
     * 
     */
    public LineaMaximaMemoriaResponse createLineaMaximaMemoriaResponse() {
        return new LineaMaximaMemoriaResponse();
    }

    /**
     * Create an instance of {@link PautasClasificacionBD }
     * 
     */
    public PautasClasificacionBD createPautasClasificacionBD() {
        return new PautasClasificacionBD();
    }

    /**
     * Create an instance of {@link DelegacionOficinaBD }
     * 
     */
    public DelegacionOficinaBD createDelegacionOficinaBD() {
        return new DelegacionOficinaBD();
    }

    /**
     * Create an instance of {@link DistribucionCargaResponse }
     * 
     */
    public DistribucionCargaResponse createDistribucionCargaResponse() {
        return new DistribucionCargaResponse();
    }

    /**
     * Create an instance of {@link ObtenerParametroProceso }
     * 
     */
    public ObtenerParametroProceso createObtenerParametroProceso() {
        return new ObtenerParametroProceso();
    }

    /**
     * Create an instance of {@link LineaMaximaBD }
     * 
     */
    public LineaMaximaBD createLineaMaximaBD() {
        return new LineaMaximaBD();
    }

    /**
     * Create an instance of {@link DelegacionOficinaMemoriaResponse }
     * 
     */
    public DelegacionOficinaMemoriaResponse createDelegacionOficinaMemoriaResponse() {
        return new DelegacionOficinaMemoriaResponse();
    }

    /**
     * Create an instance of {@link DelegacionOficinaMemoria }
     * 
     */
    public DelegacionOficinaMemoria createDelegacionOficinaMemoria() {
        return new DelegacionOficinaMemoria();
    }

    /**
     * Create an instance of {@link PautasClasificacionBDResponse }
     * 
     */
    public PautasClasificacionBDResponse createPautasClasificacionBDResponse() {
        return new PautasClasificacionBDResponse();
    }

    /**
     * Create an instance of {@link DelegacionRiesgosResponse }
     * 
     */
    public DelegacionRiesgosResponse createDelegacionRiesgosResponse() {
        return new DelegacionRiesgosResponse();
    }

    /**
     * Create an instance of {@link LineaMaximaMemoria }
     * 
     */
    public LineaMaximaMemoria createLineaMaximaMemoria() {
        return new LineaMaximaMemoria();
    }

    /**
     * Create an instance of {@link ConsultarDocumentoExpedienteResponse }
     * 
     */
    public ConsultarDocumentoExpedienteResponse createConsultarDocumentoExpedienteResponse() {
        return new ConsultarDocumentoExpedienteResponse();
    }

    /**
     * Create an instance of {@link LineaMaximaBDResponse }
     * 
     */
    public LineaMaximaBDResponse createLineaMaximaBDResponse() {
        return new LineaMaximaBDResponse();
    }

    /**
     * Create an instance of {@link ConsultarDocumentoExpediente }
     * 
     */
    public ConsultarDocumentoExpediente createConsultarDocumentoExpediente() {
        return new ConsultarDocumentoExpediente();
    }

    /**
     * Create an instance of {@link ActualizarDocumentoExpTCResponse }
     * 
     */
    public ActualizarDocumentoExpTCResponse createActualizarDocumentoExpTCResponse() {
        return new ActualizarDocumentoExpTCResponse();
    }

    /**
     * Create an instance of {@link ActualizaEmpleadoExpediente }
     * 
     */
    public ActualizaEmpleadoExpediente createActualizaEmpleadoExpediente() {
        return new ActualizaEmpleadoExpediente();
    }

    /**
     * Create an instance of {@link ObtenerUsuario }
     * 
     */
    public ObtenerUsuario createObtenerUsuario() {
        return new ObtenerUsuario();
    }

    /**
     * Create an instance of {@link DistribucionCarga }
     * 
     */
    public DistribucionCarga createDistribucionCarga() {
        return new DistribucionCarga();
    }

    /**
     * Create an instance of {@link ObtenerParametroProcesoResponse }
     * 
     */
    public ObtenerParametroProcesoResponse createObtenerParametroProcesoResponse() {
        return new ObtenerParametroProcesoResponse();
    }

    /**
     * Create an instance of {@link RetraerTareasResponse }
     * 
     */
    public RetraerTareasResponse createRetraerTareasResponse() {
        return new RetraerTareasResponse();
    }

    /**
     * Create an instance of {@link DelegacionOficinaBDResponse }
     * 
     */
    public DelegacionOficinaBDResponse createDelegacionOficinaBDResponse() {
        return new DelegacionOficinaBDResponse();
    }

    /**
     * Create an instance of {@link PautasClasificacionMemoriaResponse }
     * 
     */
    public PautasClasificacionMemoriaResponse createPautasClasificacionMemoriaResponse() {
        return new PautasClasificacionMemoriaResponse();
    }

    /**
     * Create an instance of {@link RetraerTareas }
     * 
     */
    public RetraerTareas createRetraerTareas() {
        return new RetraerTareas();
    }

    /**
     * Create an instance of {@link ActualizarDocumentoExpTC }
     * 
     */
    public ActualizarDocumentoExpTC createActualizarDocumentoExpTC() {
        return new ActualizarDocumentoExpTC();
    }

    /**
     * Create an instance of {@link PautasClasificacionMemoria }
     * 
     */
    public PautasClasificacionMemoria createPautasClasificacionMemoria() {
        return new PautasClasificacionMemoria();
    }

    /**
     * Create an instance of {@link DelegacionRiesgos }
     * 
     */
    public DelegacionRiesgos createDelegacionRiesgos() {
        return new DelegacionRiesgos();
    }

    /**
     * Create an instance of {@link EmpleadoDTO }
     * 
     */
    public EmpleadoDTO createEmpleadoDTO() {
        return new EmpleadoDTO();
    }

    /**
     * Create an instance of {@link ParametrosProcesoDTO }
     * 
     */
    public ParametrosProcesoDTO createParametrosProcesoDTO() {
        return new ParametrosProcesoDTO();
    }

    /**
     * Create an instance of {@link ExpedienteDTO }
     * 
     */
    public ExpedienteDTO createExpedienteDTO() {
        return new ExpedienteDTO();
    }

    /**
     * Create an instance of {@link PerfilDTO }
     * 
     */
    public PerfilDTO createPerfilDTO() {
        return new PerfilDTO();
    }

    /**
     * Create an instance of {@link EmpleadoVO }
     * 
     */
    public EmpleadoVO createEmpleadoVO() {
        return new EmpleadoVO();
    }

    /**
     * Create an instance of {@link EmpleadoPerfilVO }
     * 
     */
    public EmpleadoPerfilVO createEmpleadoPerfilVO() {
        return new EmpleadoPerfilVO();
    }

    /**
     * Create an instance of {@link DocumentoCM }
     * 
     */
    public DocumentoCM createDocumentoCM() {
        return new DocumentoCM();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegacionRiesgos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "delegacionRiesgos")
    public JAXBElement<DelegacionRiesgos> createDelegacionRiesgos(DelegacionRiesgos value) {
        return new JAXBElement<DelegacionRiesgos>(_DelegacionRiesgos_QNAME, DelegacionRiesgos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetraerTareasResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "retraerTareasResponse")
    public JAXBElement<RetraerTareasResponse> createRetraerTareasResponse(RetraerTareasResponse value) {
        return new JAXBElement<RetraerTareasResponse>(_RetraerTareasResponse_QNAME, RetraerTareasResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegacionOficinaMemoria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "delegacionOficinaMemoria")
    public JAXBElement<DelegacionOficinaMemoria> createDelegacionOficinaMemoria(DelegacionOficinaMemoria value) {
        return new JAXBElement<DelegacionOficinaMemoria>(_DelegacionOficinaMemoria_QNAME, DelegacionOficinaMemoria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PautasClasificacionMemoriaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "pautasClasificacionMemoriaResponse")
    public JAXBElement<PautasClasificacionMemoriaResponse> createPautasClasificacionMemoriaResponse(PautasClasificacionMemoriaResponse value) {
        return new JAXBElement<PautasClasificacionMemoriaResponse>(_PautasClasificacionMemoriaResponse_QNAME, PautasClasificacionMemoriaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PautasClasificacionBD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "pautasClasificacionBD")
    public JAXBElement<PautasClasificacionBD> createPautasClasificacionBD(PautasClasificacionBD value) {
        return new JAXBElement<PautasClasificacionBD>(_PautasClasificacionBD_QNAME, PautasClasificacionBD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineaMaximaMemoria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "lineaMaximaMemoria")
    public JAXBElement<LineaMaximaMemoria> createLineaMaximaMemoria(LineaMaximaMemoria value) {
        return new JAXBElement<LineaMaximaMemoria>(_LineaMaximaMemoria_QNAME, LineaMaximaMemoria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineaMaximaMemoriaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "lineaMaximaMemoriaResponse")
    public JAXBElement<LineaMaximaMemoriaResponse> createLineaMaximaMemoriaResponse(LineaMaximaMemoriaResponse value) {
        return new JAXBElement<LineaMaximaMemoriaResponse>(_LineaMaximaMemoriaResponse_QNAME, LineaMaximaMemoriaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizaEmpleadoExpediente }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "actualizaEmpleadoExpediente")
    public JAXBElement<ActualizaEmpleadoExpediente> createActualizaEmpleadoExpediente(ActualizaEmpleadoExpediente value) {
        return new JAXBElement<ActualizaEmpleadoExpediente>(_ActualizaEmpleadoExpediente_QNAME, ActualizaEmpleadoExpediente.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineaMaximaBDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "lineaMaximaBDResponse")
    public JAXBElement<LineaMaximaBDResponse> createLineaMaximaBDResponse(LineaMaximaBDResponse value) {
        return new JAXBElement<LineaMaximaBDResponse>(_LineaMaximaBDResponse_QNAME, LineaMaximaBDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuarioResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "obtenerUsuarioResponse")
    public JAXBElement<ObtenerUsuarioResponse> createObtenerUsuarioResponse(ObtenerUsuarioResponse value) {
        return new JAXBElement<ObtenerUsuarioResponse>(_ObtenerUsuarioResponse_QNAME, ObtenerUsuarioResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PautasClasificacionMemoria }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "pautasClasificacionMemoria")
    public JAXBElement<PautasClasificacionMemoria> createPautasClasificacionMemoria(PautasClasificacionMemoria value) {
        return new JAXBElement<PautasClasificacionMemoria>(_PautasClasificacionMemoria_QNAME, PautasClasificacionMemoria.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarDocumentoExpTC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "actualizarDocumentoExpTC")
    public JAXBElement<ActualizarDocumentoExpTC> createActualizarDocumentoExpTC(ActualizarDocumentoExpTC value) {
        return new JAXBElement<ActualizarDocumentoExpTC>(_ActualizarDocumentoExpTC_QNAME, ActualizarDocumentoExpTC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerParametroProcesoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "obtenerParametroProcesoResponse")
    public JAXBElement<ObtenerParametroProcesoResponse> createObtenerParametroProcesoResponse(ObtenerParametroProcesoResponse value) {
        return new JAXBElement<ObtenerParametroProcesoResponse>(_ObtenerParametroProcesoResponse_QNAME, ObtenerParametroProcesoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineaMaximaBD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "lineaMaximaBD")
    public JAXBElement<LineaMaximaBD> createLineaMaximaBD(LineaMaximaBD value) {
        return new JAXBElement<LineaMaximaBD>(_LineaMaximaBD_QNAME, LineaMaximaBD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegacionOficinaMemoriaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "delegacionOficinaMemoriaResponse")
    public JAXBElement<DelegacionOficinaMemoriaResponse> createDelegacionOficinaMemoriaResponse(DelegacionOficinaMemoriaResponse value) {
        return new JAXBElement<DelegacionOficinaMemoriaResponse>(_DelegacionOficinaMemoriaResponse_QNAME, DelegacionOficinaMemoriaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegacionOficinaBDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "delegacionOficinaBDResponse")
    public JAXBElement<DelegacionOficinaBDResponse> createDelegacionOficinaBDResponse(DelegacionOficinaBDResponse value) {
        return new JAXBElement<DelegacionOficinaBDResponse>(_DelegacionOficinaBDResponse_QNAME, DelegacionOficinaBDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetraerTareas }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "retraerTareas")
    public JAXBElement<RetraerTareas> createRetraerTareas(RetraerTareas value) {
        return new JAXBElement<RetraerTareas>(_RetraerTareas_QNAME, RetraerTareas.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DistribucionCargaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "distribucionCargaResponse")
    public JAXBElement<DistribucionCargaResponse> createDistribucionCargaResponse(DistribucionCargaResponse value) {
        return new JAXBElement<DistribucionCargaResponse>(_DistribucionCargaResponse_QNAME, DistribucionCargaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizaEmpleadoExpedienteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "actualizaEmpleadoExpedienteResponse")
    public JAXBElement<ActualizaEmpleadoExpedienteResponse> createActualizaEmpleadoExpedienteResponse(ActualizaEmpleadoExpedienteResponse value) {
        return new JAXBElement<ActualizaEmpleadoExpedienteResponse>(_ActualizaEmpleadoExpedienteResponse_QNAME, ActualizaEmpleadoExpedienteResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarDocumentoExpediente }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "consultarDocumentoExpediente")
    public JAXBElement<ConsultarDocumentoExpediente> createConsultarDocumentoExpediente(ConsultarDocumentoExpediente value) {
        return new JAXBElement<ConsultarDocumentoExpediente>(_ConsultarDocumentoExpediente_QNAME, ConsultarDocumentoExpediente.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuario }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "obtenerUsuario")
    public JAXBElement<ObtenerUsuario> createObtenerUsuario(ObtenerUsuario value) {
        return new JAXBElement<ObtenerUsuario>(_ObtenerUsuario_QNAME, ObtenerUsuario.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DistribucionCarga }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "distribucionCarga")
    public JAXBElement<DistribucionCarga> createDistribucionCarga(DistribucionCarga value) {
        return new JAXBElement<DistribucionCarga>(_DistribucionCarga_QNAME, DistribucionCarga.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarDocumentoExpedienteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "consultarDocumentoExpedienteResponse")
    public JAXBElement<ConsultarDocumentoExpedienteResponse> createConsultarDocumentoExpedienteResponse(ConsultarDocumentoExpedienteResponse value) {
        return new JAXBElement<ConsultarDocumentoExpedienteResponse>(_ConsultarDocumentoExpedienteResponse_QNAME, ConsultarDocumentoExpedienteResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegacionOficinaBD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "delegacionOficinaBD")
    public JAXBElement<DelegacionOficinaBD> createDelegacionOficinaBD(DelegacionOficinaBD value) {
        return new JAXBElement<DelegacionOficinaBD>(_DelegacionOficinaBD_QNAME, DelegacionOficinaBD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualizarDocumentoExpTCResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "actualizarDocumentoExpTCResponse")
    public JAXBElement<ActualizarDocumentoExpTCResponse> createActualizarDocumentoExpTCResponse(ActualizarDocumentoExpTCResponse value) {
        return new JAXBElement<ActualizarDocumentoExpTCResponse>(_ActualizarDocumentoExpTCResponse_QNAME, ActualizarDocumentoExpTCResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PautasClasificacionBDResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "pautasClasificacionBDResponse")
    public JAXBElement<PautasClasificacionBDResponse> createPautasClasificacionBDResponse(PautasClasificacionBDResponse value) {
        return new JAXBElement<PautasClasificacionBDResponse>(_PautasClasificacionBDResponse_QNAME, PautasClasificacionBDResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerParametroProceso }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "obtenerParametroProceso")
    public JAXBElement<ObtenerParametroProceso> createObtenerParametroProceso(ObtenerParametroProceso value) {
        return new JAXBElement<ObtenerParametroProceso>(_ObtenerParametroProceso_QNAME, ObtenerParametroProceso.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelegacionRiesgosResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://business.service.bbva.ibm.com/", name = "delegacionRiesgosResponse")
    public JAXBElement<DelegacionRiesgosResponse> createDelegacionRiesgosResponse(DelegacionRiesgosResponse value) {
        return new JAXBElement<DelegacionRiesgosResponse>(_DelegacionRiesgosResponse_QNAME, DelegacionRiesgosResponse.class, null, value);
    }

}
