//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package hiper.webservices.impl.hfirmas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import hiper.spring.beans.hfirmas.webservices.xsd.RpteActivacionBE;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cod_operacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usr_activacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cod_cliente" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="id_cliente" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="lista_representantes" type="{http://webservices.hfirmas.beans.spring.hiper/xsd}RpteActivacion_BE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codOperacion",
    "usrActivacion",
    "codCliente",
    "idCliente",
    "listaRepresentantes"
})
@XmlRootElement(name = "activarFirmasyPoderesEnHost")
public class ActivarFirmasyPoderesEnHost {

    @XmlElement(name = "cod_operacion", nillable = true)
    protected String codOperacion;
    @XmlElement(name = "usr_activacion", nillable = true)
    protected String usrActivacion;
    @XmlElement(name = "cod_cliente", nillable = true)
    protected String codCliente;
    @XmlElement(name = "id_cliente")
    protected Integer idCliente;
    @XmlElement(name = "lista_representantes", nillable = true)
    protected List<RpteActivacionBE> listaRepresentantes;

    /**
     * Gets the value of the codOperacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodOperacion() {
        return codOperacion;
    }

    /**
     * Sets the value of the codOperacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodOperacion(String value) {
        this.codOperacion = value;
    }

    /**
     * Gets the value of the usrActivacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsrActivacion() {
        return usrActivacion;
    }

    /**
     * Sets the value of the usrActivacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsrActivacion(String value) {
        this.usrActivacion = value;
    }

    /**
     * Gets the value of the codCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodCliente() {
        return codCliente;
    }

    /**
     * Sets the value of the codCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodCliente(String value) {
        this.codCliente = value;
    }

    /**
     * Gets the value of the idCliente property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdCliente() {
        return idCliente;
    }

    /**
     * Sets the value of the idCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdCliente(Integer value) {
        this.idCliente = value;
    }

    /**
     * Gets the value of the listaRepresentantes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listaRepresentantes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListaRepresentantes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RpteActivacionBE }
     * 
     * 
     */
    public List<RpteActivacionBE> getListaRepresentantes() {
        if (listaRepresentantes == null) {
            listaRepresentantes = new ArrayList<RpteActivacionBE>();
        }
        return this.listaRepresentantes;
    }

}
