<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://grupobbva.com.pe/sce/tc84/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SCE_TC84" targetNamespace="http://grupobbva.com.pe/sce/tc84/">
	<wsdl:documentation>
		<wsdl:appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo imported="true">
				<binding hasEncoding="false" imported="true" name="SCE_TC84_Binding" originalBindingStyle="document"/>
			</MRWSDLAppInfo>
		</wsdl:appinfo>
	</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:mrm="http://grupobbva.com.pe/sce/tc84/" targetNamespace="http://grupobbva.com.pe/sce/tc84/">
			<xsd:include schemaLocation="xsd/SCE_TC84.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="tc84_in">	
		<wsdl:part element="tns:ExtraerTipoCambioRq" name="ExtraerTipoCambioRq"/>
	</wsdl:message>
	<wsdl:message name="tc84_out">
		<wsdl:part element="tns:ExtraerTipoCambioRs" name="ExtraerTipoCambioRs"/>
	</wsdl:message>
	<wsdl:portType name="SCE_TC84_PortType">
		<wsdl:operation name="extraerTipoCambio">
			<wsdl:input message="tns:tc84_in" name="callTC84_Input"/>
			<wsdl:output message="tns:tc84_out" name="callTC84_Output"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SCE_TC84_Binding" type="tns:SCE_TC84_PortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="extraerTipoCambio">
			<soap:operation soapAction=""/>
			<wsdl:input name="callTC84_Input">
				<soap:body parts="ExtraerTipoCambioRq" use="literal"/>
			</wsdl:input>
			<wsdl:output name="callTC84_Output">
				<soap:body parts="ExtraerTipoCambioRs" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SCE_TC84_Service">
		<wsdl:port binding="tns:SCE_TC84_Binding" name="SCE_TC84_Port">
			<soap:address location="http://118.180.36.26:7802/ExtraerTipoCambio"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
