//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package pe.com.grupobbva.sce.qsp5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pe.com.grupobbva.sce.qsp5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InqPerfilUsuarioRq_QNAME = new QName("http://grupobbva.com.pe/sce/qsp5/", "InqPerfilUsuarioRq");
    private final static QName _InqPerfilUsuarioRs_QNAME = new QName("http://grupobbva.com.pe/sce/qsp5/", "InqPerfilUsuarioRs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pe.com.grupobbva.sce.qsp5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CtInqPerfilUsuarioRq }
     * 
     */
    public CtInqPerfilUsuarioRq createCtInqPerfilUsuarioRq() {
        return new CtInqPerfilUsuarioRq();
    }

    /**
     * Create an instance of {@link CtInqPerfilUsuarioRs }
     * 
     */
    public CtInqPerfilUsuarioRs createCtInqPerfilUsuarioRs() {
        return new CtInqPerfilUsuarioRs();
    }

    /**
     * Create an instance of {@link CtBodyRq }
     * 
     */
    public CtBodyRq createCtBodyRq() {
        return new CtBodyRq();
    }

    /**
     * Create an instance of {@link CtBodyRs }
     * 
     */
    public CtBodyRs createCtBodyRs() {
        return new CtBodyRs();
    }

    /**
     * Create an instance of {@link CtHeader }
     * 
     */
    public CtHeader createCtHeader() {
        return new CtHeader();
    }

    /**
     * Create an instance of {@link CtHeaderRs }
     * 
     */
    public CtHeaderRs createCtHeaderRs() {
        return new CtHeaderRs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtInqPerfilUsuarioRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/sce/qsp5/", name = "InqPerfilUsuarioRq")
    public JAXBElement<CtInqPerfilUsuarioRq> createInqPerfilUsuarioRq(CtInqPerfilUsuarioRq value) {
        return new JAXBElement<CtInqPerfilUsuarioRq>(_InqPerfilUsuarioRq_QNAME, CtInqPerfilUsuarioRq.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtInqPerfilUsuarioRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobbva.com.pe/sce/qsp5/", name = "InqPerfilUsuarioRs")
    public JAXBElement<CtInqPerfilUsuarioRs> createInqPerfilUsuarioRs(CtInqPerfilUsuarioRs value) {
        return new JAXBElement<CtInqPerfilUsuarioRs>(_InqPerfilUsuarioRs_QNAME, CtInqPerfilUsuarioRs.class, null, value);
    }

}
