//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.bbva.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.ibm.as.core.vo.AbstractVO;


/**
 * <p>Java class for EmpleadoVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmpleadoVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://vo.core.as.ibm.com}AbstractVO">
 *       &lt;sequence>
 *         &lt;element name="correo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="codigo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombres" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apepat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apemat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idPerfilFk" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fecing" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="fecegr" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="idOficinaFk" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="nombresCompletos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idNivelFk" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="idTipoCategoriaFk" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="flagActivo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmpleadoVO", propOrder = {
    "correo",
    "id",
    "codigo",
    "nombres",
    "apepat",
    "apemat",
    "idPerfilFk",
    "fecing",
    "fecegr",
    "idOficinaFk",
    "nombresCompletos",
    "idNivelFk",
    "idTipoCategoriaFk",
    "flagActivo"
})
public class EmpleadoVO
    extends AbstractVO
{

    @XmlElement(required = true, nillable = true)
    protected String correo;
    @XmlElement(required = true, type = Long.class, nillable = true)
    protected Long id;
    @XmlElement(required = true, nillable = true)
    protected String codigo;
    @XmlElement(required = true, nillable = true)
    protected String nombres;
    @XmlElement(required = true, nillable = true)
    protected String apepat;
    @XmlElement(required = true, nillable = true)
    protected String apemat;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer idPerfilFk;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fecing;
    @XmlElement(required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fecegr;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer idOficinaFk;
    @XmlElement(required = true, nillable = true)
    protected String nombresCompletos;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer idNivelFk;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer idTipoCategoriaFk;
    @XmlElement(required = true, nillable = true)
    protected String flagActivo;

    /**
     * Gets the value of the correo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorreo() {
        return correo;
    }

    /**
     * Sets the value of the correo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorreo(String value) {
        this.correo = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigo() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigo(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the nombres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * Sets the value of the nombres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombres(String value) {
        this.nombres = value;
    }

    /**
     * Gets the value of the apepat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApepat() {
        return apepat;
    }

    /**
     * Sets the value of the apepat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApepat(String value) {
        this.apepat = value;
    }

    /**
     * Gets the value of the apemat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApemat() {
        return apemat;
    }

    /**
     * Sets the value of the apemat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApemat(String value) {
        this.apemat = value;
    }

    /**
     * Gets the value of the idPerfilFk property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdPerfilFk() {
        return idPerfilFk;
    }

    /**
     * Sets the value of the idPerfilFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdPerfilFk(Integer value) {
        this.idPerfilFk = value;
    }

    /**
     * Gets the value of the fecing property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecing() {
        return fecing;
    }

    /**
     * Sets the value of the fecing property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecing(XMLGregorianCalendar value) {
        this.fecing = value;
    }

    /**
     * Gets the value of the fecegr property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecegr() {
        return fecegr;
    }

    /**
     * Sets the value of the fecegr property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecegr(XMLGregorianCalendar value) {
        this.fecegr = value;
    }

    /**
     * Gets the value of the idOficinaFk property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdOficinaFk() {
        return idOficinaFk;
    }

    /**
     * Sets the value of the idOficinaFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdOficinaFk(Integer value) {
        this.idOficinaFk = value;
    }

    /**
     * Gets the value of the nombresCompletos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombresCompletos() {
        return nombresCompletos;
    }

    /**
     * Sets the value of the nombresCompletos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombresCompletos(String value) {
        this.nombresCompletos = value;
    }

    /**
     * Gets the value of the idNivelFk property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdNivelFk() {
        return idNivelFk;
    }

    /**
     * Sets the value of the idNivelFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdNivelFk(Integer value) {
        this.idNivelFk = value;
    }

    /**
     * Gets the value of the idTipoCategoriaFk property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdTipoCategoriaFk() {
        return idTipoCategoriaFk;
    }

    /**
     * Sets the value of the idTipoCategoriaFk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdTipoCategoriaFk(Integer value) {
        this.idTipoCategoriaFk = value;
    }

    /**
     * Gets the value of the flagActivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlagActivo() {
        return flagActivo;
    }

    /**
     * Sets the value of the flagActivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlagActivo(String value) {
        this.flagActivo = value;
    }

}
