//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package com.ibm.bbva.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.ibm.as.core.vo.AbstractVO;


/**
 * <p>Java class for EmpleadoPerfilVO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmpleadoPerfilVO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://vo.core.as.ibm.com}AbstractVO">
 *       &lt;sequence>
 *         &lt;element name="empleadoVO" type="{http://vo.bbva.ibm.com}EmpleadoVO"/>
 *         &lt;element name="descripcionPerfil" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmpleadoPerfilVO", propOrder = {
    "empleadoVO",
    "descripcionPerfil"
})
public class EmpleadoPerfilVO
    extends AbstractVO
{

    @XmlElement(required = true, nillable = true)
    protected EmpleadoVO empleadoVO;
    @XmlElement(required = true, nillable = true)
    protected String descripcionPerfil;

    /**
     * Gets the value of the empleadoVO property.
     * 
     * @return
     *     possible object is
     *     {@link EmpleadoVO }
     *     
     */
    public EmpleadoVO getEmpleadoVO() {
        return empleadoVO;
    }

    /**
     * Sets the value of the empleadoVO property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmpleadoVO }
     *     
     */
    public void setEmpleadoVO(EmpleadoVO value) {
        this.empleadoVO = value;
    }

    /**
     * Gets the value of the descripcionPerfil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionPerfil() {
        return descripcionPerfil;
    }

    /**
     * Sets the value of the descripcionPerfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionPerfil(String value) {
        this.descripcionPerfil = value;
    }

}
