//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.ctacte.servicio.cm;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "CEContentManagerServiceService", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", wsdlLocation = "WEB-INF/wsdl/CEContentManagerServiceService.wsdl")
public class CEContentManagerServiceService
    extends Service
{

    private final static URL CECONTENTMANAGERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CECONTENTMANAGERSERVICESERVICE_EXCEPTION;
    private final static QName CECONTENTMANAGERSERVICESERVICE_QNAME = new QName("http://cm.servicio.ctacte.bbva.ibm.com/", "CEContentManagerServiceService");

    static {
            CECONTENTMANAGERSERVICESERVICE_WSDL_LOCATION = com.ibm.bbva.ctacte.servicio.cm.CEContentManagerServiceService.class.getResource("/WEB-INF/wsdl/CEContentManagerServiceService.wsdl");
        WebServiceException e = null;
        if (CECONTENTMANAGERSERVICESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/CEContentManagerServiceService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        CECONTENTMANAGERSERVICESERVICE_EXCEPTION = e;
    }

    public CEContentManagerServiceService() {
        super(__getWsdlLocation(), CECONTENTMANAGERSERVICESERVICE_QNAME);
    }

    public CEContentManagerServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CECONTENTMANAGERSERVICESERVICE_QNAME, features);
    }

    public CEContentManagerServiceService(URL wsdlLocation) {
        super(wsdlLocation, CECONTENTMANAGERSERVICESERVICE_QNAME);
    }

    public CEContentManagerServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CECONTENTMANAGERSERVICESERVICE_QNAME, features);
    }

    public CEContentManagerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CEContentManagerServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CEContentManagerServiceDelegate
     */
    @WebEndpoint(name = "CEContentManagerServicePort")
    public CEContentManagerServiceDelegate getCEContentManagerServicePort() {
        return super.getPort(new QName("http://cm.servicio.ctacte.bbva.ibm.com/", "CEContentManagerServicePort"), CEContentManagerServiceDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CEContentManagerServiceDelegate
     */
    @WebEndpoint(name = "CEContentManagerServicePort")
    public CEContentManagerServiceDelegate getCEContentManagerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cm.servicio.ctacte.bbva.ibm.com/", "CEContentManagerServicePort"), CEContentManagerServiceDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CECONTENTMANAGERSERVICESERVICE_EXCEPTION!= null) {
            throw CECONTENTMANAGERSERVICESERVICE_EXCEPTION;
        }
        return CECONTENTMANAGERSERVICESERVICE_WSDL_LOCATION;
    }

}
