//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.ctacte.servicio.cm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "CEContentManagerServiceDelegate", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CEContentManagerServiceDelegate {


    /**
     * 
     * @param idExpediente
     * @param idDocumento
     * @return
     *     returns com.ibm.bbva.ctacte.servicio.cm.DocumentoCM
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDocumentoCM", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoCM")
    @ResponseWrapper(localName = "obtenerDocumentoCMResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoCMResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoCMRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoCMResponse")
    public DocumentoCM obtenerDocumentoCM(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "idDocumento", targetNamespace = "")
        int idDocumento);

    /**
     * 
     * @param codigoDocumento
     * @param idExpediente
     * @return
     *     returns com.ibm.bbva.ctacte.servicio.cm.DocumentoCM
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDocumentoCMxCodigo", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoCMxCodigo")
    @ResponseWrapper(localName = "obtenerDocumentoCMxCodigoResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoCMxCodigoResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoCMxCodigoRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoCMxCodigoResponse")
    public DocumentoCM obtenerDocumentoCMxCodigo(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "codigoDocumento", targetNamespace = "")
        String codigoDocumento);

    /**
     * 
     * @param idExpediente
     * @param flagCM
     * @param pidCM
     * @param idCM
     * @param idDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "actualizarEstadoDocumento_CC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarEstadoDocumento_CC", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ActualizarEstadoDocumentoCC")
    @ResponseWrapper(localName = "actualizarEstadoDocumento_CCResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ActualizarEstadoDocumentoCCResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/actualizarEstadoDocumento_CCRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/actualizarEstadoDocumento_CCResponse")
    public String actualizarEstadoDocumentoCC(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "idDocumento", targetNamespace = "")
        int idDocumento,
        @WebParam(name = "flagCM", targetNamespace = "")
        String flagCM,
        @WebParam(name = "idCM", targetNamespace = "")
        int idCM,
        @WebParam(name = "pidCM", targetNamespace = "")
        String pidCM);

    /**
     * 
     * @param codigoDocumento
     * @param idExpediente
     * @param flagCM
     * @param pidCM
     * @param idCM
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "actualizarEstadoDocumentoxCodigo_CC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarEstadoDocumentoxCodigo_CC", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ActualizarEstadoDocumentoxCodigoCC")
    @ResponseWrapper(localName = "actualizarEstadoDocumentoxCodigo_CCResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ActualizarEstadoDocumentoxCodigoCCResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/actualizarEstadoDocumentoxCodigo_CCRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/actualizarEstadoDocumentoxCodigo_CCResponse")
    public String actualizarEstadoDocumentoxCodigoCC(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "codigoDocumento", targetNamespace = "")
        String codigoDocumento,
        @WebParam(name = "flagCM", targetNamespace = "")
        String flagCM,
        @WebParam(name = "idCM", targetNamespace = "")
        int idCM,
        @WebParam(name = "pidCM", targetNamespace = "")
        String pidCM);

    /**
     * 
     * @param codigoDocumento
     * @param idCMCopia
     * @param idExpediente
     * @param pidCM
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "actualizarDocumentoExp_IdCMCopia")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarDocumentoExp_IdCMCopia", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ActualizarDocumentoExpIdCMCopia")
    @ResponseWrapper(localName = "actualizarDocumentoExp_IdCMCopiaResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ActualizarDocumentoExpIdCMCopiaResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/actualizarDocumentoExp_IdCMCopiaRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/actualizarDocumentoExp_IdCMCopiaResponse")
    public String actualizarDocumentoExpIdCMCopia(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "codigoDocumento", targetNamespace = "")
        String codigoDocumento,
        @WebParam(name = "idCMCopia", targetNamespace = "")
        int idCMCopia,
        @WebParam(name = "pidCM", targetNamespace = "")
        String pidCM);

    /**
     * 
     * @param codigoDocumento
     * @param idExpediente
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "obtenerDocumentoxCodigo_CC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDocumentoxCodigo_CC", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoxCodigoCC")
    @ResponseWrapper(localName = "obtenerDocumentoxCodigo_CCResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoxCodigoCCResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoxCodigo_CCRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoxCodigo_CCResponse")
    public Integer obtenerDocumentoxCodigoCC(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "codigoDocumento", targetNamespace = "")
        String codigoDocumento);

    /**
     * 
     * @param codigoDocumento
     * @param idExpediente
     * @return
     *     returns com.ibm.bbva.ctacte.servicio.cm.DocumentoExpediente
     */
    @WebMethod(operationName = "obtenerDocumentoExpediente_CC")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerDocumentoExpediente_CC", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoExpedienteCC")
    @ResponseWrapper(localName = "obtenerDocumentoExpediente_CCResponse", targetNamespace = "http://cm.servicio.ctacte.bbva.ibm.com/", className = "com.ibm.bbva.ctacte.servicio.cm.ObtenerDocumentoExpedienteCCResponse")
    @Action(input = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoExpediente_CCRequest", output = "http://cm.servicio.ctacte.bbva.ibm.com/CEContentManagerServiceDelegate/obtenerDocumentoExpediente_CCResponse")
    public DocumentoExpediente obtenerDocumentoExpedienteCC(
        @WebParam(name = "idExpediente", targetNamespace = "")
        int idExpediente,
        @WebParam(name = "codigoDocumento", targetNamespace = "")
        String codigoDocumento);

}
