//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.cm.service.impl.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "actualizarTipoDoc", namespace = "http://impl.service.cm.bbva.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actualizarTipoDoc", namespace = "http://impl.service.cm.bbva.ibm.com/", propOrder = {
    "id",
    "tipoDoc"
})
public class ActualizarTipoDoc {

    @XmlElement(name = "id", namespace = "")
    private Integer id;
    @XmlElement(name = "tipoDoc", namespace = "")
    private String tipoDoc;

    /**
     * 
     * @return
     *     returns Integer
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 
     * @param id
     *     the value for the id property
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getTipoDoc() {
        return this.tipoDoc;
    }

    /**
     * 
     * @param tipoDoc
     *     the value for the tipoDoc property
     */
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }

}
