//
// Generated By:JAX-WS RI IBM 2.2.1-11/25/2013 11:48 AM(foreman)- (JAXB RI IBM 2.2.3-11/25/2013 12:35 PM(foreman)-)
//


package pe.com.grupobbva.accpj;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "ACCPJ_ServiciosWeb_Service", targetNamespace = "http://grupobbva.com.pe/accpj/", wsdlLocation = "META-INF/wsdl/ACCPJ_ServiciosWebService.wsdl")
public class ACCPJServiciosWebService
    extends Service
{

    private final static URL ACCPJSERVICIOSWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCPJSERVICIOSWEBSERVICE_EXCEPTION;
    private final static QName ACCPJSERVICIOSWEBSERVICE_QNAME = new QName("http://grupobbva.com.pe/accpj/", "ACCPJ_ServiciosWeb_Service");

    static {
            ACCPJSERVICIOSWEBSERVICE_WSDL_LOCATION = pe.com.grupobbva.accpj.ACCPJServiciosWebService.class.getResource("/META-INF/wsdl/ACCPJ_ServiciosWebService.wsdl");
        WebServiceException e = null;
        if (ACCPJSERVICIOSWEBSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ACCPJ_ServiciosWebService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ACCPJSERVICIOSWEBSERVICE_EXCEPTION = e;
    }

    public ACCPJServiciosWebService() {
        super(__getWsdlLocation(), ACCPJSERVICIOSWEBSERVICE_QNAME);
    }

    public ACCPJServiciosWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCPJSERVICIOSWEBSERVICE_QNAME, features);
    }

    public ACCPJServiciosWebService(URL wsdlLocation) {
        super(wsdlLocation, ACCPJSERVICIOSWEBSERVICE_QNAME);
    }

    public ACCPJServiciosWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCPJSERVICIOSWEBSERVICE_QNAME, features);
    }

    public ACCPJServiciosWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ACCPJServiciosWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ACCPJServiciosWebPortType
     */
    @WebEndpoint(name = "ACCPJ_ServiciosWeb_Port")
    public ACCPJServiciosWebPortType getACCPJServiciosWebPort() {
        return super.getPort(new QName("http://grupobbva.com.pe/accpj/", "ACCPJ_ServiciosWeb_Port"), ACCPJServiciosWebPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ACCPJServiciosWebPortType
     */
    @WebEndpoint(name = "ACCPJ_ServiciosWeb_Port")
    public ACCPJServiciosWebPortType getACCPJServiciosWebPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://grupobbva.com.pe/accpj/", "ACCPJ_ServiciosWeb_Port"), ACCPJServiciosWebPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCPJSERVICIOSWEBSERVICE_EXCEPTION!= null) {
            throw ACCPJSERVICIOSWEBSERVICE_EXCEPTION;
        }
        return ACCPJSERVICIOSWEBSERVICE_WSDL_LOCATION;
    }

}
