CREATE TABLE PUBLIC.TBL_PYME_PARAMETER
(ID_TABLE INTEGER NOT NULL,
ID_COLUMN CHAR(3) NOT NULL,
ID_REFERENCE VARCHAR(3),
VAL_COLUMN1 VARCHAR(256),
VAL_COLUMN2 VARCHAR(128),
FLG_STATE INTEGER DEFAULT 1,
PRIMARY KEY (ID_TABLE, ID_COLUMN));


INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (1, '001', '', 'APROBADO', '', 0);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (1, '002', '', 'PRE-APROBADO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (1, '003', '', 'REFERIDO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (1, '004', '', 'NINGUNO', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (2, '000', '', 'NINGUNA', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (2, '001', '', 'TKT', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (2, '002', '', 'PRESTAMO COMERCIAL RAPIMONTO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (2, '003', '', 'PRESTAMO COMERCIAL SUBROGACION', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (2, '004', '', 'PRESTAMO COMERCIAL ESTACIONAL', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (2, '005', '', 'PRESTAMO COMERCIAL ADEX', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (3, '001', '', 'TARJETA CAPITAL DE TRABAJO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (3, '002', '', 'PRESTAMO COMERCIAL', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (4, '000', '', '', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (4, '001', '', 'ACN ARENALES', '0734|0736|0737|0674', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (4, '002', '', 'ACN LOS OLIVOS', '0644|6133', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (4, '003', '', 'ACN SANTA ANITA', '0644|6133', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (4, '004', '', 'ACN VILLA EL SALVADOR', '0630', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '001', '', 'ENVIADO A MESA CONTROL', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '002', '', 'DEVUELTO POR MESA CONTROL', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '003', '', 'APROBADO CON MODIFICACION POR CONFIRMAR', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '004', '', 'ENVIADO A EVALUACION', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '005', '', 'DEVUELTO A MESA CONTROL', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '006', '', 'APROBADO SIN MODIFICACION', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '007', '', 'APROBADO CON MODIFICACION', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '008', '', 'DENEGADO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '009', '', 'DESEMBOLSADO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '010', '', 'CANCELADO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (5, '011', '', 'EN ESPERA TRAMITE GARANTIA', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (6, '000', '', '', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (6, '001', '', 'No acepta monto modificado', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (6, '002', '', 'No acepta condiciones de tasa', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (6, '003', '', 'No acepta condiciones de plazo', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (6, '004', '', 'Desistio por demoras en respuesta', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (6, '005', '', 'No acepta condiciones de cuota inicial', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (7, '000', '', 'NINGUNO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (7, '001', '', 'Documentacion del check list incompleta', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (7, '002', '', 'Coeficientes SUNAT incontrastables', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (7, '003', '', 'Rating no ingresado', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (7, '004', '', 'No corresponde a segmento Banca Negocios', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (7, '005', '', 'No corresponde a segmento 60-450', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '001', '', 'http://118.180.54.185:7811/tx_firmas', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '002', '', 'P105274', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '003', '', '118.180.54.25', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '004', '', '25', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '005', '', 'administrador.cs@bbva.com', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '006', '', '', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (8, '007', '', 'contratacionelectronica.peru@bbva.com', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '001', '001', '- DJ Anual SUNAT (Reg. General, sólo 5 primeras páginas, si es cliente con Rating adjuntar las 21 páginas) + Constancia de Presentación.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '002', '001', '- 3 Últimos PDT mensuales (RG y RE) + Constancia de Presentación, para RUS (Guía de pagos varios + vouchers de pago).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '003', '001', '- Extracto de declaraciones y pagos SUNAT anual para RG y RER. 3 Últimos pagos SUNAT.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '004', '001', '- DNI de los participantes (RRLL y Avales).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '005', '001', '- Informe Comercial (antigüedad < 6 meses y firmado por el cliente).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '006', '001', '- Declaración Jurada patrimonial del cliente (antigüedad < 6 meses y firmado por el cliente).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '007', '001', '- Informe de visita (solo para operaciones procedentes de la FF.VV.).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '008', '001', '- Para clientes PJ nuevos adjuntar Copia Literal no mayor a 30 días.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '009', '001', '- Si el cliente presenta OP vigentes, adjuntar reportes de crédito anterior (titular, grupo económico o vinculadas).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '010', '001', '- Sustento de patrimonio (PU+HR, SUNARP, COFOPRI, Compra - Venta) + Contrato de alquiler de locales comerciales/ almacenes.<BR>', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '021', '002', 'En el caso de colegios, planillas UGEL del año en curso.', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '022', '002', 'En el caso de Transporte interprovincial/carga, licencia de Ruta del MTC/Gob.Regional, tarjeta de propiedad, SOAT, N° de unidades.', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '023', '002', 'En el caso de Pesca, permisos de capitanía de las embarcaciones y permisos de asignación de cuotas de pesca.', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '024', '002', 'En el caso de transporte fluvial, permisos de capitania de las embarcaciones.', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '025', '002', 'En el caso de extracción de madera, permisos de INRENA.', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '026', '002', 'En el caso de restaurantes, copia de la carta de platos y sustento del número de mesas.', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '027', '002', 'En el caso de contratistas, back log documentado (contratos ganados, contratos de consorcio y liquidaciones de obra).', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '028', '002', 'Permisos de funcionamiento (hoteles, venta de combustible, entidades educativas, laboratorios, centros de salud, boticas)', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '031', '003', '- Contratos pre - impresos.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '036', '006', '- Para financiamientos > 12 meses, si es bien mueble, adjuntar proforma. Para construcción adjuntar presupuesto detallado firmado Ing. o Arq. Para compra venta indicar nombre del vendedor.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '037', '006', '- Para compra de deuda, adjuntar los cronogramas de deudas comerciales de los otros bancos y sustentar el destino del financiamiento.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '041', '004', '- Reporte de Crédito.<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '042', '004', '- Metodizado según DJ Anual SUNAT (solo para clientes que estén en el giro de construcción, contratistas, agentes de aduanas, asesorías, dotación de personal o servicios).<BR>', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (9, '046', '005', '- Fotos de fachada y almacén(es) para todos los segmentos y FUVEX. [Se deberá adjuntar en formato .jpg o .png].<BR>', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (10, '001', '', '1', 'Activacion de LDAP', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (10, '002', '', 'ldap://118.180.54.179:389/o=igrupobbva', 'IP LDAP', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (10, '003', '', '720', 'Horas de verificacion datos usuario IDM', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (10, '004', '', 'D:\BBVA\PYMES\FUENTES\WFFastPymeBBVA', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (11, '001', '', 'APROBADO SIN MODIFICACION', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (11, '002', '', 'APROBADO CON MODIFICACION', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (11, '003', '', 'DENEGADO', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (11, '004', '', 'REQUISITO OBSERVADO', '', 1);

INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (12, '001', '', 'Grupo 1: DOCUMENTACION SUSTENTATORIO/ECONOMICA DEL CLIENTE', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (12, '002', '', 'Grupo 2: DOCUMENTACION ESPECIFICA', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (12, '003', '', 'Grupo 3: CONTRATOS', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (12, '004', '', 'Grupo 4: REPORTE DE CREDITO Y METODIZADO [Se debe adjuntar en formato .xls, cada formato va en 1 pestaña del excel].', '', 1);
INSERT INTO PUBLIC.TBL_PYME_PARAMETER (ID_TABLE, ID_COLUMN, ID_REFERENCE, VAL_COLUMN1, VAL_COLUMN2, FLG_STATE) VALUES (12, '005', '', 'Grupo 5: FOTOS DEL NEGOCIO', '', 1);