DELETE FROM CONELE.TBL_CE_IBM_PERFIL_BALANCEO_CC;
DELETE FROM CONELE.TBL_CE_IBM_AUDIT_BASTANTEO_CC;  
DELETE FROM CONELE.TBL_CE_IBM_AUDIT_CLIENTE_CC;    
DELETE FROM CONELE.TBL_CE_IBM_AUDIT_CRITERIOS_CC;  
DELETE FROM CONELE.TBL_CE_IBM_TIPO_BALANCEO_CC;
DELETE FROM CONELE.TBL_CE_IBM_COBRO_COMISION_CC;
DELETE FROM CONELE.TBL_CE_IBM_ESCANEO_WEB_CC;
DELETE FROM CONELE.TBL_CE_IBM_LISTA_CERRADA_CC;
DELETE FROM CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC;
DELETE FROM CONELE.TBL_CE_IBM_PARA_VISTA_UNICA_CC; 
DELETE FROM CONELE.TBL_CE_IBM_PESO_EXP_CC; 
DELETE FROM CONELE.TBL_CE_IBM_PESO_PARTICIPE_CC;   
DELETE FROM CONELE.TBL_CE_IBM_PLAZO_SUBSANA_CC;   

DELETE FROM CONELE.TBL_CE_IBM_LOG_CC;              
DELETE FROM CONELE.TBL_CE_IBM_GUIA_DOCUMENT_CC;  
DELETE FROM CONELE.TBL_CE_IBM_PARTICIPE_CC;   
DELETE FROM CONELE.TBL_CE_IBM_EXP_CUENTA_CC;  
DELETE FROM CONELE.TBL_CE_IBM_CUENTA_CC;                 

DELETE FROM CONELE.TBL_CE_IBM_DOCUMENTO_EXP_CC; 
DELETE FROM CONELE.TBL_CE_IBM_DOCUMENTO_HIST_CC;
DELETE FROM CONELE.TBL_CE_IBM_DOCUMENTO_CC;
DELETE FROM CONELE.TBL_CE_IBM_EXPEDIENTE_TAREA_CC; 
DELETE FROM CONELE.TBL_CE_IBM_EXPTAR_PROCESO_CC;
DELETE FROM CONELE.TBL_CE_IBM_AYUDA_MEMORIA_CC;    
DELETE FROM CONELE.TBL_CE_IBM_HISTORIAL_CC;  
DELETE FROM CONELE.TBL_CE_IBM_EXPEDIENTE_CC; 
DELETE FROM CONELE.TBL_CE_IBM_CLIENTE_CC;   
DELETE FROM CONELE.TBL_CE_IBM_TAREAS_REASIG_CC;    
DELETE FROM CONELE.TBL_CE_IBM_MOTIVO_CC; 

DELETE FROM CONELE.TBL_CE_IBM_CAMPANIA_CC;         
DELETE FROM CONELE.TBL_CE_IBM_ESTADO_EXP_CC;       
DELETE FROM CONELE.TBL_CE_IBM_ESTADO_TAREA_CC;

DELETE FROM CONELE.TBL_CE_IBM_CARTERIZACION;

DELETE FROM CONELE.TBL_CE_IBM_TAREA_PERFIL_CC;
DELETE FROM CONELE.TBL_CE_IBM_TAREA_CC;           

DELETE FROM CONELE.TBL_CE_IBM_OPERACION_CC;   
DELETE FROM CONELE.TBL_CE_IBM_PRODUCTO_CC;  

DELETE FROM CONELE.TBL_CE_IBM_EMPLEADO;					
DELETE FROM CONELE.TBL_CE_IBM_PERFIL;					
DELETE FROM CONELE.TBL_CE_IBM_PRODUCTO;					
DELETE FROM CONELE.TBL_CE_IBM_ESTUDIO_ABOGADO_CC;         
COMMIT;