	DROP TABLE CONELE.TBL_CE_IBM_PERFIL_BALANCEO_CC;
	DROP TABLE CONELE.TBL_CE_IBM_AUDIT_BASTANTEO_CC;  
	DROP TABLE CONELE.TBL_CE_IBM_AUDIT_CLIENTE_CC;    
	DROP TABLE CONELE.TBL_CE_IBM_AUDIT_CRITERIOS_CC;  
	DROP TABLE CONELE.TBL_CE_IBM_TIPO_BALANCEO_CC;
	DROP TABLE CONELE.TBL_CE_IBM_COBRO_COMISION_CC;
	DROP TABLE CONELE.TBL_CE_IBM_ESCANEO_WEB_CC;
	DROP TABLE CONELE.TBL_CE_IBM_LISTA_CERRADA_CC;
	DROP TABLE CONELE.TBL_CE_IBM_PARAMETROS_CONF_CC;
	DROP TABLE CONELE.TBL_CE_IBM_PARA_VISTA_UNICA_CC; 
	DROP TABLE CONELE.TBL_CE_IBM_PESO_EXP_CC; 
	DROP TABLE CONELE.TBL_CE_IBM_PESO_PARTICIPE_CC;   
	DROP TABLE CONELE.TBL_CE_IBM_PLAZO_SUBSANA_CC;   


	DROP TABLE CONELE.TBL_CE_IBM_LOG_CC;              
	DROP TABLE CONELE.TBL_CE_IBM_GUIA_DOCUMENT_CC;  
	DROP TABLE CONELE.TBL_CE_IBM_PARTICIPE_CC;   
	DROP TABLE CONELE.TBL_CE_IBM_EXP_CUENTA_CC;  
	DROP TABLE CONELE.TBL_CE_IBM_CUENTA_CC;                 


	DROP TABLE CONELE.TBL_CE_IBM_DOCUMENTO_EXP_CC; 
	DROP TABLE CONELE.TBL_CE_IBM_DOCUMENTO_HIST_CC;
	DROP TABLE CONELE.TBL_CE_IBM_DOCUMENTO_CC;
	DROP TABLE CONELE.TBL_CE_IBM_EXPEDIENTE_TAREA_CC; 
	DROP TABLE CONELE.TBL_CE_IBM_EXPTAR_PROCESO_CC;
	DROP TABLE CONELE.TBL_CE_IBM_AYUDA_MEMORIA_CC;   
	DROP TABLE CONELE.TBL_CE_IBM_TAREAS_REASIG_CC;     
	DROP TABLE CONELE.TBL_CE_IBM_HISTORIAL_CC;  
	DROP TABLE CONELE.TBL_CE_IBM_EXPEDIENTE_CC; 
	DROP TABLE CONELE.TBL_CE_IBM_CLIENTE_CC;   

	DROP TABLE CONELE.TBL_CE_IBM_MOTIVO_CC; 


	DROP TABLE CONELE.TBL_CE_IBM_CAMPANIA_CC;         
	DROP TABLE CONELE.TBL_CE_IBM_ESTADO_EXP_CC;       
	DROP TABLE CONELE.TBL_CE_IBM_ESTADO_TAREA_CC;

	DROP TABLE CONELE.TBL_CE_IBM_CARTERIZACION;

	DROP TABLE CONELE.TBL_CE_IBM_TAREA_PERFIL_CC;
	DROP TABLE CONELE.TBL_CE_IBM_TAREA_CC;           

	DROP TABLE CONELE.TBL_CE_IBM_OPERACION_CC;   
	DROP TABLE CONELE.TBL_CE_IBM_PRODUCTO_CC;  

	--DROP TABLE CONELE.TBL_CE_IBM_HORARIO_OFICINA; 
	--DROP TABLE CONELE.TBL_CE_IBM_HORARIO; 
	DROP TABLE CONELE.TBL_CE_IBM_EMPLEADO;					
	DROP TABLE CONELE.TBL_CE_IBM_PERFIL;					
	--DROP TABLE CONELE.TBL_CE_IBM_OFICINA;  	--Adicional para pruebas
	--DROP TABLE CONELE.TBL_CE_IBM_TERRITORIO;  --Adicional para pruebas           
	--DROP TABLE CONELE.TBL_CE_IBM_VALORES_FORANEOS;
	--DROP TABLE CONELE.TBL_CE_IBM_POSIBLE_VALOR;       
	--DROP TABLE CONELE.TBL_CE_IBM_COLUMNA;             
	--DROP TABLE CONELE.TBL_CE_IBM_TABLA;             
	DROP TABLE CONELE.TBL_CE_IBM_PRODUCTO;					
	DROP TABLE CONELE.TBL_CE_IBM_ESTUDIO_ABOGADO_CC;         


	DROP VIEW CONELE.VIEW_CE_IBM_NUMERO_EXPEDIENTES; 
	DROP VIEW CONELE.VIEW_CE_IBM_NUMERO_PARTICIPES; 
	DROP VIEW CONELE.VIEW_CE_IBM_SUMA_PESODOC_EXP; 
	DROP VIEW CONELE.VIEW_CE_IBM_PESO_EXP_EMP; 
	DROP VIEW CONELE.VIEW_CE_IBM_PESO_PARTICIPE_EXP;