//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.proxy.ext;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pe.com.bbva.ws.ldap.servidor.ext package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObtenerPuestosResponse_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerPuestosResponse");
    private final static QName _ObtenerUsuarios_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerUsuarios");
    private final static QName _ObtenerUsuariosPorEmpresaResponse_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerUsuariosPorEmpresaResponse");
    private final static QName _WSLdapException_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "WSLdapException");
    private final static QName _ObtenerPuestos_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerPuestos");
    private final static QName _ObtenerPerfilesPorUsuarioyAplicacionResponse_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerPerfilesPorUsuarioyAplicacionResponse");
    private final static QName _ObtenerPerfilesResponse_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerPerfilesResponse");
    private final static QName _ObtenerUsuariosResponse_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerUsuariosResponse");
    private final static QName _ObtenerUsuariosPorPerfilResponse_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerUsuariosPorPerfilResponse");
    private final static QName _ObtenerPerfiles_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerPerfiles");
    private final static QName _ObtenerPerfilesPorUsuarioyAplicacion_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerPerfilesPorUsuarioyAplicacion");
    private final static QName _ObtenerUsuariosPorEmpresa_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerUsuariosPorEmpresa");
    private final static QName _ObtenerUsuariosPorPerfil_QNAME = new QName("http://ext.servidor.ldap.ws.bbva.com.pe/", "obtenerUsuariosPorPerfil");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pe.com.bbva.ws.ldap.servidor.ext
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerUsuariosPorPerfil }
     * 
     */
    public ObtenerUsuariosPorPerfil createObtenerUsuariosPorPerfil() {
        return new ObtenerUsuariosPorPerfil();
    }

    /**
     * Create an instance of {@link ObtenerUsuariosPorPerfilResponse }
     * 
     */
    public ObtenerUsuariosPorPerfilResponse createObtenerUsuariosPorPerfilResponse() {
        return new ObtenerUsuariosPorPerfilResponse();
    }

    /**
     * Create an instance of {@link WSLdapException }
     * 
     */
    public WSLdapException createWSLdapException() {
        return new WSLdapException();
    }

    /**
     * Create an instance of {@link ObtenerPuestos }
     * 
     */
    public ObtenerPuestos createObtenerPuestos() {
        return new ObtenerPuestos();
    }

    /**
     * Create an instance of {@link ObtenerPuestosResponse }
     * 
     */
    public ObtenerPuestosResponse createObtenerPuestosResponse() {
        return new ObtenerPuestosResponse();
    }

    /**
     * Create an instance of {@link ObtenerPerfiles }
     * 
     */
    public ObtenerPerfiles createObtenerPerfiles() {
        return new ObtenerPerfiles();
    }

    /**
     * Create an instance of {@link ObtenerPerfilesResponse }
     * 
     */
    public ObtenerPerfilesResponse createObtenerPerfilesResponse() {
        return new ObtenerPerfilesResponse();
    }

    /**
     * Create an instance of {@link ObtenerUsuariosPorEmpresa }
     * 
     */
    public ObtenerUsuariosPorEmpresa createObtenerUsuariosPorEmpresa() {
        return new ObtenerUsuariosPorEmpresa();
    }

    /**
     * Create an instance of {@link ObtenerUsuariosPorEmpresaResponse }
     * 
     */
    public ObtenerUsuariosPorEmpresaResponse createObtenerUsuariosPorEmpresaResponse() {
        return new ObtenerUsuariosPorEmpresaResponse();
    }

    /**
     * Create an instance of {@link ObtenerPerfilesPorUsuarioyAplicacion }
     * 
     */
    public ObtenerPerfilesPorUsuarioyAplicacion createObtenerPerfilesPorUsuarioyAplicacion() {
        return new ObtenerPerfilesPorUsuarioyAplicacion();
    }

    /**
     * Create an instance of {@link ObtenerUsuarios }
     * 
     */
    public ObtenerUsuarios createObtenerUsuarios() {
        return new ObtenerUsuarios();
    }

    /**
     * Create an instance of {@link ObtenerPerfilesPorUsuarioyAplicacionResponse }
     * 
     */
    public ObtenerPerfilesPorUsuarioyAplicacionResponse createObtenerPerfilesPorUsuarioyAplicacionResponse() {
        return new ObtenerPerfilesPorUsuarioyAplicacionResponse();
    }

    /**
     * Create an instance of {@link ObtenerUsuariosResponse }
     * 
     */
    public ObtenerUsuariosResponse createObtenerUsuariosResponse() {
        return new ObtenerUsuariosResponse();
    }

    /**
     * Create an instance of {@link Centro }
     * 
     */
    public Centro createCentro() {
        return new Centro();
    }

    /**
     * Create an instance of {@link GenericBean }
     * 
     */
    public GenericBean createGenericBean() {
        return new GenericBean();
    }

    /**
     * Create an instance of {@link PuestoExtendido }
     * 
     */
    public PuestoExtendido createPuestoExtendido() {
        return new PuestoExtendido();
    }

    /**
     * Create an instance of {@link UsuarioExtendido }
     * 
     */
    public UsuarioExtendido createUsuarioExtendido() {
        return new UsuarioExtendido();
    }

    /**
     * Create an instance of {@link Perfil }
     * 
     */
    public Perfil createPerfil() {
        return new Perfil();
    }

    /**
     * Create an instance of {@link Puesto }
     * 
     */
    public Puesto createPuesto() {
        return new Puesto();
    }

    /**
     * Create an instance of {@link Usuario }
     * 
     */
    public Usuario createUsuario() {
        return new Usuario();
    }

    /**
     * Create an instance of {@link PerfilesUsuario }
     * 
     */
    public PerfilesUsuario createPerfilesUsuario() {
        return new PerfilesUsuario();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerPuestosResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerPuestosResponse")
    public JAXBElement<ObtenerPuestosResponse> createObtenerPuestosResponse(ObtenerPuestosResponse value) {
        return new JAXBElement<ObtenerPuestosResponse>(_ObtenerPuestosResponse_QNAME, ObtenerPuestosResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuarios }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerUsuarios")
    public JAXBElement<ObtenerUsuarios> createObtenerUsuarios(ObtenerUsuarios value) {
        return new JAXBElement<ObtenerUsuarios>(_ObtenerUsuarios_QNAME, ObtenerUsuarios.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuariosPorEmpresaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerUsuariosPorEmpresaResponse")
    public JAXBElement<ObtenerUsuariosPorEmpresaResponse> createObtenerUsuariosPorEmpresaResponse(ObtenerUsuariosPorEmpresaResponse value) {
        return new JAXBElement<ObtenerUsuariosPorEmpresaResponse>(_ObtenerUsuariosPorEmpresaResponse_QNAME, ObtenerUsuariosPorEmpresaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSLdapException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "WSLdapException")
    public JAXBElement<WSLdapException> createWSLdapException(WSLdapException value) {
        return new JAXBElement<WSLdapException>(_WSLdapException_QNAME, WSLdapException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerPuestos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerPuestos")
    public JAXBElement<ObtenerPuestos> createObtenerPuestos(ObtenerPuestos value) {
        return new JAXBElement<ObtenerPuestos>(_ObtenerPuestos_QNAME, ObtenerPuestos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerPerfilesPorUsuarioyAplicacionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerPerfilesPorUsuarioyAplicacionResponse")
    public JAXBElement<ObtenerPerfilesPorUsuarioyAplicacionResponse> createObtenerPerfilesPorUsuarioyAplicacionResponse(ObtenerPerfilesPorUsuarioyAplicacionResponse value) {
        return new JAXBElement<ObtenerPerfilesPorUsuarioyAplicacionResponse>(_ObtenerPerfilesPorUsuarioyAplicacionResponse_QNAME, ObtenerPerfilesPorUsuarioyAplicacionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerPerfilesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerPerfilesResponse")
    public JAXBElement<ObtenerPerfilesResponse> createObtenerPerfilesResponse(ObtenerPerfilesResponse value) {
        return new JAXBElement<ObtenerPerfilesResponse>(_ObtenerPerfilesResponse_QNAME, ObtenerPerfilesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuariosResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerUsuariosResponse")
    public JAXBElement<ObtenerUsuariosResponse> createObtenerUsuariosResponse(ObtenerUsuariosResponse value) {
        return new JAXBElement<ObtenerUsuariosResponse>(_ObtenerUsuariosResponse_QNAME, ObtenerUsuariosResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuariosPorPerfilResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerUsuariosPorPerfilResponse")
    public JAXBElement<ObtenerUsuariosPorPerfilResponse> createObtenerUsuariosPorPerfilResponse(ObtenerUsuariosPorPerfilResponse value) {
        return new JAXBElement<ObtenerUsuariosPorPerfilResponse>(_ObtenerUsuariosPorPerfilResponse_QNAME, ObtenerUsuariosPorPerfilResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerPerfiles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerPerfiles")
    public JAXBElement<ObtenerPerfiles> createObtenerPerfiles(ObtenerPerfiles value) {
        return new JAXBElement<ObtenerPerfiles>(_ObtenerPerfiles_QNAME, ObtenerPerfiles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerPerfilesPorUsuarioyAplicacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerPerfilesPorUsuarioyAplicacion")
    public JAXBElement<ObtenerPerfilesPorUsuarioyAplicacion> createObtenerPerfilesPorUsuarioyAplicacion(ObtenerPerfilesPorUsuarioyAplicacion value) {
        return new JAXBElement<ObtenerPerfilesPorUsuarioyAplicacion>(_ObtenerPerfilesPorUsuarioyAplicacion_QNAME, ObtenerPerfilesPorUsuarioyAplicacion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuariosPorEmpresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerUsuariosPorEmpresa")
    public JAXBElement<ObtenerUsuariosPorEmpresa> createObtenerUsuariosPorEmpresa(ObtenerUsuariosPorEmpresa value) {
        return new JAXBElement<ObtenerUsuariosPorEmpresa>(_ObtenerUsuariosPorEmpresa_QNAME, ObtenerUsuariosPorEmpresa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObtenerUsuariosPorPerfil }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ext.servidor.ldap.ws.bbva.com.pe/", name = "obtenerUsuariosPorPerfil")
    public JAXBElement<ObtenerUsuariosPorPerfil> createObtenerUsuariosPorPerfil(ObtenerUsuariosPorPerfil value) {
        return new JAXBElement<ObtenerUsuariosPorPerfil>(_ObtenerUsuariosPorPerfil_QNAME, ObtenerUsuariosPorPerfil.class, null, value);
    }

}
