//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.ibm.bbva.proxy.ext;

import javax.xml.ws.WebFault;

@WebFault(name = "WSLdapException", targetNamespace = "http://ext.servidor.ldap.ws.bbva.com.pe/")
public class WSLdapException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WSLdapException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WSLdapException_Exception(String message, WSLdapException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public WSLdapException_Exception(String message, WSLdapException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pe.com.bbva.ws.ldap.servidor.ext.WSLdapException
     */
    public WSLdapException getFaultInfo() {
        return faultInfo;
    }

}
