//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package pe.com.grupobbva.sce.tc84;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ctBodyRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ctBodyRs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fechaCambio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoCambio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="divisaBase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="entidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tipos" type="{http://grupobbva.com.pe/sce/tc84/}ctTipos" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ctBodyRs", propOrder = {
    "fechaCambio",
    "tipoCambio",
    "divisaBase",
    "entidad",
    "tipos"
})
public class CtBodyRs {

    @XmlElement(required = true)
    protected String fechaCambio;
    @XmlElement(required = true)
    protected String tipoCambio;
    @XmlElement(required = true)
    protected String divisaBase;
    @XmlElement(required = true)
    protected String entidad;
    @XmlElement(name = "Tipos")
    protected CtTipos tipos;

    /**
     * Gets the value of the fechaCambio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaCambio() {
        return fechaCambio;
    }

    /**
     * Sets the value of the fechaCambio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaCambio(String value) {
        this.fechaCambio = value;
    }

    /**
     * Gets the value of the tipoCambio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCambio() {
        return tipoCambio;
    }

    /**
     * Sets the value of the tipoCambio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCambio(String value) {
        this.tipoCambio = value;
    }

    /**
     * Gets the value of the divisaBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivisaBase() {
        return divisaBase;
    }

    /**
     * Sets the value of the divisaBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivisaBase(String value) {
        this.divisaBase = value;
    }

    /**
     * Gets the value of the entidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the tipos property.
     * 
     * @return
     *     possible object is
     *     {@link CtTipos }
     *     
     */
    public CtTipos getTipos() {
        return tipos;
    }

    /**
     * Sets the value of the tipos property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtTipos }
     *     
     */
    public void setTipos(CtTipos value) {
        this.tipos = value;
    }

}
